const shield = [
  {
    category: "Shield",
    name: "Bronze Shield",
    cost: 100,
    def: 2,
    mdef: 0,
  },
  {
    category: "Shield",
    name: "Runic Shield",
    cost: 150,
    def: 2,
    mdef: 2,
  },
  {
    category: "Armor",
    name: "Silk Shirt",
    cost: 100,
    def: 0,
    mdef: 2,
    armor: true,
    martial: false,
  },
  {
    category: "Armor",
    name: "Travel Garb",
    cost: 100,
    def: 1,
    mdef: 1,
    armor: true,
    martial: false,
  },
  {
    category: "Armor",
    name: "Combat Tunic",
    cost: 150,
    def: 2,
    mdef: 0,
    armor: true,
    martial: false,
  },
  {
    category: "Armor",
    name: "Sage Robe",
    cost: 200,
    def: 1,
    mdef: 2,
    armor: true,
    martial: false,
  },
  {
    category: "Armor",
    name: "Brigadine",
    cost: 150,
    def: 10,
    mdef: 0,
    armor: true,
    martial: true,
  },
  {
    category: "Armor",
    name: "Bronze Plate",
    cost: 200,
    def: 11,
    mdef: 0,
    armor: true,
    martial: true,
  },
  {
    category: "Armor",
    name: "Runic Plate",
    cost: 250,
    def: 11,
    mdef: 1,
    armor: true,
    martial: true,
  },
  {
    category: "Armor",
    name: "Steel Plate",
    cost: 300,
    def: 12,
    mdef: 0,
    armor: true,
    martial: true,
  },
];

export default shield;
