import type { ItemFieldConfig } from "../../fieldConfig";
import type { PlayerSpellFormState } from "./types";
import { isArcanist, isArcanistRework } from "./predicates";

export const arcanistFields: ItemFieldConfig<PlayerSpellFormState> = [
  {
    key: "domain",
    kind: "editable",
    label: "Domain name",
    component: "text",
    defaultValue: "",
    group: "arcanist",
    order: 90,
    gridSize: { xs: 12, sm: 4 },
    dependencies: isArcanist,
  },
  {
    key: "domainDesc",
    kind: "editable",
    label: "Domain effect",
    component: "textarea",
    defaultValue: "",
    group: "arcanist",
    order: 91,
    fullWidth: true,
    dependencies: isArcanist,
  },
  {
    key: "merge",
    kind: "editable",
    label: "Merge name",
    component: "text",
    defaultValue: "",
    group: "arcanist",
    order: 92,
    gridSize: { xs: 12, sm: 4 },
    dependencies: isArcanist,
  },
  {
    key: "mergeDesc",
    kind: "editable",
    label: "Merge effect",
    component: "textarea",
    defaultValue: "",
    group: "arcanist",
    order: 93,
    fullWidth: true,
    dependencies: isArcanist,
  },
  {
    key: "pulse",
    kind: "editable",
    label: "Pulse name",
    component: "text",
    defaultValue: "",
    group: "arcanist",
    order: 94,
    gridSize: { xs: 12, sm: 4 },
    dependencies: isArcanistRework,
  },
  {
    key: "pulseDesc",
    kind: "editable",
    label: "Pulse effect",
    component: "textarea",
    defaultValue: "",
    group: "arcanist",
    order: 95,
    fullWidth: true,
    dependencies: isArcanistRework,
  },
  {
    key: "dismiss",
    kind: "editable",
    label: "Dismiss name",
    component: "text",
    defaultValue: "",
    group: "arcanist",
    order: 96,
    gridSize: { xs: 12, sm: 4 },
    dependencies: isArcanist,
  },
  {
    key: "dismissDesc",
    kind: "editable",
    label: "Dismiss effect",
    component: "textarea",
    defaultValue: "",
    group: "arcanist",
    order: 97,
    fullWidth: true,
    dependencies: isArcanist,
  },
];
