import type { ItemFieldConfig } from "../../fieldConfig";
import { typeOptions } from "../../typeOptions";
import type { PlayerSpellFormState } from "./types";
import {
  STANDARD_SPELL_CLASSES,
  SPELL_CLASS_OPTIONS,
  ATTR_OPTIONS,
  DURATION_OPTIONS,
  TARGET_OPTIONS,
} from "./options";
import { isDefault, showDuration } from "./predicates";
import { SHARED_LABEL_KEYS, prefixedLabel } from "../sharedLabelKeys";

const SPELL_LABEL_PREFIX = "spell";

export const defaultFields: ItemFieldConfig<PlayerSpellFormState> = [
  {
    key: "class",
    kind: "editable",
    label: prefixedLabel(SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.class),
    component: "select",
    defaultValue: STANDARD_SPELL_CLASSES[0],
    group: "core",
    order: 1,
    gridSize: { xs: 12, sm: 7 },
    dependencies: isDefault,
    componentProps: { options: SPELL_CLASS_OPTIONS },
  },
  {
    key: "isOffensive",
    kind: "editable",
    label: prefixedLabel(SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.offensive),
    component: "offensive-toggle",
    defaultValue: false,
    group: "core",
    order: 5,
    gridSize: "auto",
    dependencies: isDefault,
  },
  {
    key: "cost.resource",
    kind: "computed",
    label: "shared.cost.resource",
    defaultValue: "mp" as const,
    group: "cost",
    order: 20,
  },
  {
    key: "cost.amount",
    kind: "editable",
    label: (s) =>
      s["cost.perTarget"]
        ? "shared.cost.amountPerTarget"
        : "shared.cost.amount",
    component: "number",
    defaultValue: 0,
    group: "cost",
    order: 21,
    gridSize: "auto",
    parse: (v) => Number(v) || 0,
    dependencies: isDefault,
  },
  {
    key: "cost.perTarget",
    kind: "editable",
    label: "shared.cost.perTarget",
    component: "checkbox",
    defaultValue: true,
    group: "cost",
    order: 22,
    gridSize: "auto",
    dependencies: isDefault,
  },
  {
    key: "maxTargets",
    kind: "editable",
    label: prefixedLabel(SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.maxTargets),
    component: "number",
    defaultValue: 1,
    group: "cost",
    order: 23,
    gridSize: "auto",
    parse: (v) => Number(v) || 0,
    validationHints: { min: 0 },
    dependencies: isDefault,
  },
  {
    key: "targetDescription",
    kind: "editable",
    label: prefixedLabel(SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.target),
    component: "autocomplete",
    defaultValue: "One creature",
    group: "target",
    order: 30,
    gridSize: { xs: 12, sm: 6 },
    dependencies: isDefault,
    componentProps: { options: TARGET_OPTIONS, freeSolo: true },
  },
  {
    key: "duration",
    kind: "editable",
    label: prefixedLabel(SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.duration),
    component: "autocomplete",
    defaultValue: "Instantaneous",
    group: "target",
    order: 31,
    gridSize: { xs: 12, sm: 6 },
    dependencies: showDuration,
    componentProps: { options: DURATION_OPTIONS, freeSolo: true },
  },
  {
    key: "accuracy.attr1",
    kind: "editable",
    label: "shared.accuracy.attr1",
    component: "select",
    defaultValue: "insight",
    group: "accuracy",
    order: 40,
    gridSize: { xs: 6, sm: 3 },
    dependencies: isDefault,
    componentProps: { options: ATTR_OPTIONS },
  },
  {
    key: "accuracy.attr2",
    kind: "editable",
    label: "shared.accuracy.attr2",
    component: "select",
    defaultValue: "will",
    group: "accuracy",
    order: 41,
    gridSize: { xs: 6, sm: 3 },
    dependencies: isDefault,
    componentProps: { options: ATTR_OPTIONS },
  },
  {
    key: "accuracy.value",
    kind: "computed",
    label: "shared.accuracy.bonus",
    defaultValue: 0,
    group: "accuracy",
    order: 42,
  },
  {
    key: "accuracy.defense",
    kind: "computed",
    label: "shared.accuracy.defense",
    defaultValue: "mdef" as const,
    group: "accuracy",
    order: 43,
  },
  {
    key: "damage.value",
    kind: "editable",
    label: "shared.damage.value",
    component: "number",
    defaultValue: 0,
    group: "damage",
    order: 50,
    gridSize: { xs: 6, sm: 3 },
    parse: (v) => Number(v) || 0,
    dependencies: (s) => isDefault(s) && s.isOffensive,
  },
  {
    key: "damage.type",
    kind: "editable",
    label: "shared.damage.type",
    component: "type-select",
    defaultValue: "physical",
    group: "damage",
    order: 51,
    gridSize: { xs: 6, sm: 3 },
    componentProps: { options: typeOptions },
    dependencies: (s) => isDefault(s) && s.isOffensive,
  },
  {
    key: "damage.hrZero",
    kind: "editable",
    label: "shared.damage.hrZero",
    component: "checkbox",
    defaultValue: false,
    group: "damage",
    order: 52,
    gridSize: { xs: 12, sm: 3 },
    dependencies: (s) => isDefault(s) && s.isOffensive,
  },
  {
    key: "description",
    kind: "editable",
    label: prefixedLabel(SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.description),
    component: "textarea",
    defaultValue: "",
    group: "description",
    order: 60,
    fullWidth: true,
    dependencies: isDefault,
  },
  {
    key: "showInPlayerSheet",
    kind: "editable",
    label: "Show in Character Sheet",
    component: "checkbox",
    defaultValue: true,
    group: "visibility",
    order: 70,
    gridSize: { xs: 12 },
    dependencies: isDefault,
  },
  {
    key: "isMagisphere",
    kind: "editable",
    label: "Is a Magisphere?",
    component: "checkbox",
    defaultValue: false,
    group: "visibility",
    order: 71,
    gridSize: { xs: 12 },
    dependencies: isDefault,
  },
];
