import type { ItemFieldConfig } from "../../fieldConfig";
import { typeOptions } from "../../typeOptions";
import type { PlayerSpellFormState } from "./types";
import {
  STANDARD_SPELL_CLASSES,
  SPELL_CLASS_OPTIONS,
  ATTR_OPTIONS,
  DURATION_OPTIONS,
  TARGET_OPTIONS,
} from "./options";
import { isDefault, showDuration } from "./predicates";

export const defaultFields: ItemFieldConfig<PlayerSpellFormState> = [
  {
    key: "class",
    kind: "editable",
    label: "spell.class",
    component: "select",
    defaultValue: STANDARD_SPELL_CLASSES[0],
    group: "core",
    order: 1,
    gridSize: { xs: 12, sm: 7 },
    dependencies: isDefault,
    componentProps: { options: SPELL_CLASS_OPTIONS },
  },
  {
    key: "isOffensive",
    kind: "editable",
    label: "spell.offensive",
    component: "offensive-toggle",
    defaultValue: false,
    group: "core",
    order: 5,
    gridSize: "auto",
    dependencies: isDefault,
  },
  {
    key: "cost.resource",
    kind: "computed",
    label: "spell.cost.resource",
    defaultValue: "mp" as const,
    group: "cost",
    order: 20,
  },
  {
    key: "cost.amount",
    kind: "editable",
    label: (s) => (s["cost.perTarget"] ? "spell.cost.amountPerTarget" : "spell.cost.amount"),
    component: "number",
    defaultValue: 0,
    group: "cost",
    order: 21,
    gridSize: "auto",
    parse: (v) => Number(v) || 0,
    dependencies: isDefault,
  },
  {
    key: "cost.perTarget",
    kind: "editable",
    label: "spell.cost.perTarget",
    component: "checkbox",
    defaultValue: true,
    group: "cost",
    order: 22,
    gridSize: "auto",
    dependencies: isDefault,
  },
  {
    key: "maxTargets",
    kind: "editable",
    label: "spell.maxTargets",
    component: "number",
    defaultValue: 1,
    group: "cost",
    order: 23,
    gridSize: "auto",
    parse: (v) => Number(v) || 0,
    validationHints: { min: 0 },
    dependencies: isDefault,
  },
  {
    key: "targetDescription",
    kind: "editable",
    label: "spell.target",
    component: "autocomplete",
    defaultValue: "One creature",
    group: "target",
    order: 30,
    gridSize: { xs: 12, sm: 6 },
    dependencies: isDefault,
    componentProps: { options: TARGET_OPTIONS, freeSolo: true },
  },
  {
    key: "duration",
    kind: "editable",
    label: "spell.duration",
    component: "autocomplete",
    defaultValue: "Instantaneous",
    group: "target",
    order: 31,
    gridSize: { xs: 12, sm: 6 },
    dependencies: showDuration,
    componentProps: { options: DURATION_OPTIONS, freeSolo: true },
  },
  {
    key: "accuracy.attr1",
    kind: "editable",
    label: "spell.accuracy.attr1",
    component: "select",
    defaultValue: "insight",
    group: "accuracy",
    order: 40,
    gridSize: { xs: 6, sm: 3 },
    dependencies: isDefault,
    componentProps: { options: ATTR_OPTIONS },
  },
  {
    key: "accuracy.attr2",
    kind: "editable",
    label: "spell.accuracy.attr2",
    component: "select",
    defaultValue: "will",
    group: "accuracy",
    order: 41,
    gridSize: { xs: 6, sm: 3 },
    dependencies: isDefault,
    componentProps: { options: ATTR_OPTIONS },
  },
  {
    key: "accuracy.value",
    kind: "computed",
    label: "spell.accuracy.bonus",
    defaultValue: 0,
    group: "accuracy",
    order: 42,
  },
  {
    key: "accuracy.defense",
    kind: "computed",
    label: "spell.accuracy.defense",
    defaultValue: "mdef" as const,
    group: "accuracy",
    order: 43,
  },
  {
    key: "damage.value",
    kind: "editable",
    label: "spell.damage.value",
    component: "number",
    defaultValue: 0,
    group: "damage",
    order: 50,
    gridSize: { xs: 6, sm: 3 },
    parse: (v) => Number(v) || 0,
    dependencies: (s) => isDefault(s) && s.isOffensive,
  },
  {
    key: "damage.type",
    kind: "editable",
    label: "spell.damage.type",
    component: "type-select",
    defaultValue: "physical",
    group: "damage",
    order: 51,
    gridSize: { xs: 6, sm: 3 },
    componentProps: { options: typeOptions },
    dependencies: (s) => isDefault(s) && s.isOffensive,
  },
  {
    key: "damage.hrZero",
    kind: "editable",
    label: "spell.damage.hrZero",
    component: "checkbox",
    defaultValue: false,
    group: "damage",
    order: 52,
    gridSize: { xs: 12, sm: 3 },
    dependencies: (s) => isDefault(s) && s.isOffensive,
  },
  {
    key: "description",
    kind: "editable",
    label: "spell.description",
    component: "textarea",
    defaultValue: "",
    group: "description",
    order: 60,
    fullWidth: true,
    dependencies: isDefault,
  },
];
