import type { ItemFieldConfig } from "../../fieldConfig";
import type { PlayerSpellFormState } from "./types";
import { isMagiseed } from "./predicates";

export const magiseedFields: ItemFieldConfig<PlayerSpellFormState> = [
  {
    key: "class",
    kind: "computed",
    label: "spell.class",
    defaultValue: "Floralist",
    group: "core",
    order: 1,
    dependencies: isMagiseed,
  },
  {
    key: "rangeStart",
    kind: "editable",
    label: "magiseed.rangeStart",
    component: "number",
    defaultValue: 0,
    group: "effect",
    order: 10,
    gridSize: { xs: 6, sm: 3 },
    parse: (v) => Number(v) || 0,
    dependencies: isMagiseed,
  },
  {
    key: "rangeEnd",
    kind: "editable",
    label: "magiseed.rangeEnd",
    component: "number",
    defaultValue: 3,
    group: "effect",
    order: 11,
    gridSize: { xs: 6, sm: 3 },
    parse: (v) => Number(v) || 3,
    dependencies: isMagiseed,
  },
  {
    key: "effects.0",
    kind: "editable",
    label: "magiseed.effect_0",
    component: "textarea",
    defaultValue: "",
    group: "effect",
    order: 20,
    fullWidth: true,
    dependencies: (s: PlayerSpellFormState) => isMagiseed(s) && (s.rangeStart ?? 0) <= 0 && (s.rangeEnd ?? 3) >= 0,
  },
  {
    key: "effects.1",
    kind: "editable",
    label: "magiseed.effect_1",
    component: "textarea",
    defaultValue: "",
    group: "effect",
    order: 21,
    fullWidth: true,
    dependencies: (s: PlayerSpellFormState) => isMagiseed(s) && (s.rangeStart ?? 0) <= 1 && (s.rangeEnd ?? 3) >= 1,
  },
  {
    key: "effects.2",
    kind: "editable",
    label: "magiseed.effect_2",
    component: "textarea",
    defaultValue: "",
    group: "effect",
    order: 22,
    fullWidth: true,
    dependencies: (s: PlayerSpellFormState) => isMagiseed(s) && (s.rangeStart ?? 0) <= 2 && (s.rangeEnd ?? 3) >= 2,
  },
  {
    key: "effects.3",
    kind: "editable",
    label: "magiseed.effect_3",
    component: "textarea",
    defaultValue: "",
    group: "effect",
    order: 23,
    fullWidth: true,
    dependencies: (s: PlayerSpellFormState) => isMagiseed(s) && (s.rangeStart ?? 0) <= 3 && (s.rangeEnd ?? 3) >= 3,
  },
  {
    key: "showInPlayerSheet",
    kind: "editable",
    label: "Show in Character Sheet",
    component: "checkbox",
    defaultValue: true,
    group: "visibility",
    order: 70,
    gridSize: { xs: 12 },
    dependencies: isMagiseed,
  },
  {
    key: "gardenDescription",
    kind: "editable",
    label: "magiseed_garden_appearance",
    component: "textarea",
    defaultValue: "",
    group: "description",
    order: 71,
    fullWidth: true,
    dependencies: isMagiseed,
  },
  {
    key: "description",
    kind: "editable",
    label: "spell.magiseed.description",
    component: "textarea",
    defaultValue: "",
    group: "description",
    order: 72,
    fullWidth: true,
    dependencies: isMagiseed,
  },
];
