import { availableFrames } from "../../../../../libs/pilotVehicleData";
import type { ItemFieldConfig } from "../../fieldConfig";
import type { PlayerSpellFormState } from "./types";
import {
  isPilot,
  isPilotFrame,
  isPilotArmor,
  isPilotWeapon,
  isPilotNonFrame,
} from "./predicates";
import {
  PILOT_SUBTYPE_OPTIONS,
  FRAME_OPTIONS,
  PILOT_WEAPON_CATEGORY_OPTIONS,
  PILOT_DAMAGE_TYPE_OPTIONS,
  PILOT_RANGE_OPTIONS,
  PILOT_ATTR_OPTIONS,
} from "./options";

export const pilotVehicleFields: ItemFieldConfig<PlayerSpellFormState> = [
  {
    key: "pilotSubtype",
    kind: "editable",
    label: "Component Type",
    component: "select",
    defaultValue: "frame",
    group: "pilot",
    order: 120,
    gridSize: 12,
    dependencies: isPilot,
    componentProps: { options: PILOT_SUBTYPE_OPTIONS },
  },
  {
    key: "vehicleFrame",
    kind: "editable",
    label: "Frame",
    component: "select",
    defaultValue: (availableFrames as Array<Record<string, unknown>>)[0]?.name ?? "",
    group: "pilot",
    order: 121,
    gridSize: 12,
    dependencies: isPilotFrame,
    componentProps: { options: FRAME_OPTIONS },
  },
  {
    key: "moduleCost",
    kind: "editable",
    label: "Cost",
    component: "number",
    defaultValue: 0,
    group: "pilot",
    order: 122,
    gridSize: { xs: 6, sm: 4 },
    parse: (v) => Number(v) || 0,
    validationHints: { min: 0 },
    dependencies: isPilotNonFrame,
  },
  {
    key: "moduleDef",
    kind: "editable",
    label: "DEF",
    component: "number",
    defaultValue: 0,
    group: "pilot",
    order: 123,
    gridSize: { xs: 4, sm: 3 },
    parse: (v) => Number(v) || 0,
    dependencies: isPilotArmor,
  },
  {
    key: "moduleMdef",
    kind: "editable",
    label: "MDEF",
    component: "number",
    defaultValue: 0,
    group: "pilot",
    order: 124,
    gridSize: { xs: 4, sm: 3 },
    parse: (v) => Number(v) || 0,
    dependencies: isPilotArmor,
  },
  {
    key: "moduleMartial",
    kind: "editable",
    label: "Martial",
    component: "martial-toggle",
    defaultValue: false,
    group: "pilot",
    order: 125,
    gridSize: { xs: 4, sm: 2 },
    dependencies: isPilotArmor,
  },
  {
    key: "moduleDescription",
    kind: "editable",
    label: "Description (optional)",
    component: "textarea",
    defaultValue: "",
    group: "pilot",
    order: 126,
    fullWidth: true,
    dependencies: isPilotArmor,
  },
  {
    key: "weaponCategory",
    kind: "editable",
    label: "Category",
    component: "select",
    defaultValue: "Heavy",
    group: "pilot",
    order: 127,
    gridSize: { xs: 6, sm: 4 },
    dependencies: isPilotWeapon,
    componentProps: { options: PILOT_WEAPON_CATEGORY_OPTIONS },
  },
  {
    key: "pilotDamageType",
    kind: "editable",
    label: "Damage Type",
    component: "select",
    defaultValue: "physical",
    group: "pilot",
    order: 128,
    gridSize: { xs: 6, sm: 4 },
    dependencies: isPilotWeapon,
    componentProps: { options: PILOT_DAMAGE_TYPE_OPTIONS },
  },
  {
    key: "moduleRange",
    kind: "editable",
    label: "Range",
    component: "select",
    defaultValue: "Melee",
    group: "pilot",
    order: 129,
    gridSize: { xs: 6, sm: 4 },
    dependencies: isPilotWeapon,
    componentProps: { options: PILOT_RANGE_OPTIONS },
  },
  {
    key: "pilotAtt1",
    kind: "editable",
    label: "Att 1",
    component: "select",
    defaultValue: "might",
    group: "pilot",
    order: 130,
    gridSize: { xs: 6, sm: 3 },
    dependencies: isPilotWeapon,
    componentProps: { options: PILOT_ATTR_OPTIONS },
  },
  {
    key: "pilotAtt2",
    kind: "editable",
    label: "Att 2",
    component: "select",
    defaultValue: "dexterity",
    group: "pilot",
    order: 131,
    gridSize: { xs: 6, sm: 3 },
    dependencies: isPilotWeapon,
    componentProps: { options: PILOT_ATTR_OPTIONS },
  },
  {
    key: "moduleDamage",
    kind: "editable",
    label: "HR+",
    component: "number",
    defaultValue: 0,
    group: "pilot",
    order: 132,
    gridSize: { xs: 4, sm: 2 },
    parse: (v) => Number(v) || 0,
    dependencies: isPilotWeapon,
  },
  {
    key: "modulePrec",
    kind: "editable",
    label: "+Acc",
    component: "number",
    defaultValue: 0,
    group: "pilot",
    order: 133,
    gridSize: { xs: 4, sm: 2 },
    parse: (v) => Number(v) || 0,
    dependencies: isPilotWeapon,
  },
  {
    key: "qualityCost",
    kind: "editable",
    label: "Quality Cost",
    component: "number",
    defaultValue: 0,
    group: "pilot",
    order: 134,
    gridSize: { xs: 4, sm: 2 },
    parse: (v) => Number(v) || 0,
    dependencies: isPilotWeapon,
  },
  {
    key: "quality",
    kind: "editable",
    label: "Quality",
    component: "text",
    defaultValue: "",
    group: "pilot",
    order: 135,
    gridSize: 12,
    dependencies: isPilotWeapon,
  },
  {
    key: "moduleCumbersome",
    kind: "editable",
    label: "Cumbersome",
    component: "checkbox",
    defaultValue: false,
    group: "pilot",
    order: 136,
    gridSize: { xs: 6, sm: 6 },
    dependencies: isPilotWeapon,
  },
  {
    key: "isShield",
    kind: "editable",
    label: "Shield",
    component: "checkbox",
    defaultValue: false,
    group: "pilot",
    order: 137,
    gridSize: { xs: 6, sm: 6 },
    dependencies: isPilotWeapon,
  },
];
