import type { ItemFieldConfig } from "../fieldConfig";
import type { TypeNpc } from "../../../../types/Npcs";
import armorList from "../../../../libs/armor";
import shieldList from "../../../../libs/shields";
import { applySpeciesEffects } from "./npcSpeciesEffects";

type NpcFormState = TypeNpc & Record<string, unknown>;

const SPECIES_OPTIONS = [
  { value: "Beast", label: "Beast" },
  { value: "Construct", label: "Construct" },
  { value: "Demon", label: "Demon" },
  { value: "Elemental", label: "Elemental" },
  { value: "Monster", label: "Monster" },
  { value: "Plant", label: "Plant" },
  { value: "Undead", label: "Undead" },
  { value: "Humanoid", label: "Humanoid" },
  { value: "Variant Humanoid", label: "Variant Humanoid" },
];

const RANK_OPTIONS = [
  { value: "soldier", label: "Soldier" },
  { value: "elite", label: "Elite" },
  { value: "champion1", label: "Champion(1)" },
  { value: "champion2", label: "Champion(2)" },
  { value: "champion3", label: "Champion(3)" },
  { value: "champion4", label: "Champion(4)" },
  { value: "champion5", label: "Champion(5)" },
  { value: "champion6", label: "Champion(6)" },
  { value: "companion", label: "Companion" },
  { value: "groupvehicle", label: "Group Vehicle" },
];

const VILLAIN_OPTIONS = [
  { value: "", label: "None" },
  { value: "minor", label: "minor_villain" },
  { value: "major", label: "major_villain" },
  { value: "supreme", label: "supreme_villain" },
];

const COMPANION_LVL_OPTIONS = [1, 2, 3, 4, 5].map((n) => ({
  value: n,
  label: String(n),
}));

const SIZE_OPTIONS = [
  { value: "", label: "None" },
  { value: "small", label: "Small" },
  { value: "medium", label: "Medium" },
  { value: "large", label: "Large" },
];

const notCompanion = (s: NpcFormState) => s.rank !== "companion";
const isCompanion = (s: NpcFormState) => s.rank === "companion";
const isGroupVehicle = (s: NpcFormState) => s.rank === "groupvehicle";
const noDefOverride = (s: NpcFormState) =>
  !(s.extra as TypeNpc["extra"])?.defOverride &&
  !(s.extra as TypeNpc["extra"])?.mDefOverride;

const ATTR_SLIDER = { min: 6, max: 12, step: 2, showMarks: false };

export const npcFieldConfig: ItemFieldConfig<NpcFormState> = [
  // basics
  {
    key: "name",
    kind: "editable",
    label: "Name:",
    component: "text",
    group: "basics",
    order: 0,
    gridSize: { xs: 12, sm: 4 } as unknown as number,
    validationHints: { required: true },
  },
  {
    key: "traits",
    kind: "editable",
    label: "Traits:",
    component: "text",
    group: "basics",
    order: 1,
    gridSize: { xs: 12, sm: 8 } as unknown as number,
  },
  {
    key: "species",
    kind: "editable",
    label: "Species:",
    component: "select",
    group: "basics",
    order: 3,
    gridSize: 4,
    componentProps: { options: SPECIES_OPTIONS },
    onChangeEffects: {
      affinities: (s) => applySpeciesEffects(s.species as string).affinities,
      immunities: (s) => applySpeciesEffects(s.species as string).immunities,
    },
  },
  {
    key: "rank",
    kind: "editable",
    label: "Rank:",
    component: "select",
    group: "basics",
    order: 4,
    gridSize: 4,
    componentProps: { options: RANK_OPTIONS },
  },
  {
    key: "phases",
    kind: "editable",
    label: "Phases:",
    component: "number",
    group: "basics",
    order: 5,
    gridSize: 4,
    defaultValue: 0,
    parse: (v) => Number(v) || 0,
  },
  {
    key: "villain",
    kind: "editable",
    label: "Villain:",
    component: "select",
    group: "basics",
    order: 6,
    gridSize: 8,
    componentProps: { options: VILLAIN_OPTIONS },
    dependencies: notCompanion,
  },
  {
    key: "companionlvl",
    kind: "editable",
    label: "Skill Level:",
    component: "select",
    group: "basics",
    order: 6,
    gridSize: 4,
    componentProps: { options: COMPANION_LVL_OPTIONS },
    dependencies: isCompanion,
    defaultValue: 1,
    parse: (v) => Number(v),
  },
  {
    key: "companionpclvl",
    kind: "editable",
    label: "PC Level:",
    component: "number",
    group: "basics",
    order: 7,
    gridSize: 4,
    dependencies: isCompanion,
    defaultValue: 5,
    parse: (v) => Number(v) || 5,
  },
  {
    key: "multipart",
    kind: "editable",
    label: "Multi-Part:",
    component: "text",
    group: "basics",
    order: 8,
    fullWidth: true,
  },
  {
    key: "sizes",
    kind: "editable",
    label: "Vehicle Size:",
    component: "select",
    group: "basics",
    order: 9,
    gridSize: 4,
    componentProps: { options: SIZE_OPTIONS },
    dependencies: isGroupVehicle,
  },
  {
    key: "description",
    kind: "editable",
    label: "Description:",
    component: "textarea",
    group: "basics",
    order: 10,
    fullWidth: true,
  },

  // attributes
  {
    key: "attributes.dexterity",
    kind: "editable",
    label: "DEX",
    component: "npc-attr-slider",
    group: "attributes",
    order: 0,
    fullWidth: true,
    componentProps: ATTR_SLIDER,
  },
  {
    key: "attributes.insight",
    kind: "editable",
    label: "INS",
    component: "npc-attr-slider",
    group: "attributes",
    order: 1,
    fullWidth: true,
    componentProps: ATTR_SLIDER,
  },
  {
    key: "attributes.might",
    kind: "editable",
    label: "MIG",
    component: "npc-attr-slider",
    group: "attributes",
    order: 2,
    fullWidth: true,
    componentProps: ATTR_SLIDER,
  },
  {
    key: "attributes.will",
    kind: "editable",
    label: "WLP",
    component: "npc-attr-slider",
    group: "attributes",
    order: 3,
    fullWidth: true,
    componentProps: { ...ATTR_SLIDER, showMarks: true },
  },

  // affinities — last entry (poison) shows the full vu/rs/im/ab legend
  {
    key: "affinities.physical",
    kind: "editable",
    label: "Physical",
    component: "npc-affinity-slider",
    group: "affinities",
    order: 0,
    fullWidth: true,
    componentProps: { showLabels: false },
  },
  {
    key: "affinities.air",
    kind: "editable",
    label: "Air",
    component: "npc-affinity-slider",
    group: "affinities",
    order: 1,
    fullWidth: true,
    componentProps: { showLabels: false },
  },
  {
    key: "affinities.bolt",
    kind: "editable",
    label: "Bolt",
    component: "npc-affinity-slider",
    group: "affinities",
    order: 2,
    fullWidth: true,
    componentProps: { showLabels: false },
  },
  {
    key: "affinities.dark",
    kind: "editable",
    label: "Dark",
    component: "npc-affinity-slider",
    group: "affinities",
    order: 3,
    fullWidth: true,
    componentProps: { showLabels: false },
  },
  {
    key: "affinities.earth",
    kind: "editable",
    label: "Earth",
    component: "npc-affinity-slider",
    group: "affinities",
    order: 4,
    fullWidth: true,
    componentProps: { showLabels: false },
  },
  {
    key: "affinities.fire",
    kind: "editable",
    label: "Fire",
    component: "npc-affinity-slider",
    group: "affinities",
    order: 5,
    fullWidth: true,
    componentProps: { showLabels: false },
  },
  {
    key: "affinities.ice",
    kind: "editable",
    label: "Ice",
    component: "npc-affinity-slider",
    group: "affinities",
    order: 6,
    fullWidth: true,
    componentProps: { showLabels: false },
  },
  {
    key: "affinities.light",
    kind: "editable",
    label: "Light",
    component: "npc-affinity-slider",
    group: "affinities",
    order: 7,
    fullWidth: true,
    componentProps: { showLabels: false },
  },
  {
    key: "affinities.poison",
    kind: "editable",
    label: "Poison",
    component: "npc-affinity-slider",
    group: "affinities",
    order: 8,
    fullWidth: true,
    componentProps: { showLabels: true },
  },

  // defenses — hidden when defOverride or mDefOverride is active
  {
    key: "extra",
    kind: "editable",
    label: "Defenses",
    component: "npc-defense-radio",
    group: "defenses",
    order: 0,
    gridSize: 12,
    parse: (v) => v,
    dependencies: noDefOverride,
  },
  {
    key: "armor",
    kind: "editable",
    label: "Armor",
    component: "npc-armor-select",
    group: "defenses",
    order: 1,
    gridSize: 12,
    componentProps: { items: armorList },
    dependencies: noDefOverride,
  },
  {
    key: "shield",
    kind: "editable",
    label: "Shield",
    component: "npc-armor-select",
    group: "defenses",
    order: 2,
    gridSize: 12,
    componentProps: { items: shieldList },
    dependencies: noDefOverride,
  },

  // stats
  {
    key: "extra.hp",
    kind: "editable",
    label: "Extra HP:",
    component: "number",
    group: "stats",
    order: 0,
    fullWidth: true,
    defaultValue: 0,
    parse: (v) => Number(v) || 0,
  },
  {
    key: "extra.mp",
    kind: "editable",
    label: "Extra MP:",
    component: "number",
    group: "stats",
    order: 1,
    fullWidth: true,
    defaultValue: 0,
    parse: (v) => Number(v) || 0,
  },
  {
    key: "extra.extrainit",
    kind: "editable",
    label: "Extra Init:",
    component: "number",
    group: "stats",
    order: 2,
    fullWidth: true,
    defaultValue: 0,
    parse: (v) => Number(v) || 0,
  },
  {
    key: "extra.init",
    kind: "editable",
    label: "+4 Initiative",
    component: "checkbox",
    group: "stats",
    order: 3,
    fullWidth: true,
  },
  {
    key: "extra.precision",
    kind: "editable",
    label: "+3 bonus to all Accuracy Checks",
    component: "checkbox",
    group: "stats",
    order: 4,
    fullWidth: true,
  },
  {
    key: "extra.magic",
    kind: "editable",
    label: "+3 bonus to all Magic Checks",
    component: "checkbox",
    group: "stats",
    order: 5,
    fullWidth: true,
  },
  // extra.statusImmunity rendered manually in EditExtra to show SP-cost helper text

  // immunities — freeImmunities injected via extraProps at render time
  {
    key: "immunities",
    kind: "editable",
    label: "Immunities",
    component: "npc-immunities",
    group: "immunities",
    order: 0,
    fullWidth: true,
  },

  // publish
  {
    key: "createdBy",
    kind: "editable",
    label: "Created By:",
    component: "text",
    group: "publish",
    order: 0,
    fullWidth: true,
  },
];
