export type FormSurface = "quickCreate" | "create" | "edit";

export interface SurfaceFieldParity {
  quickCreate: readonly string[];
  create: readonly string[];
  edit: readonly string[];
}

const WEAPON_FIELDS = [
  "itemType",
  "name",
  "description",
  "category",
  "range",
  "hands",
  "martial",
  "accuracy",
  "damage",
  "modifiers",
  "rare",
  "quality",
  "cost",
  "special",
  "meta",
  "base",
  "fuid",
  "passives",
  "behaviors",
  "att1",
  "att2",
  "type",
  "damageHrZero",
  "rareBonuses",
  "precModifier",
  "damageModifier",
  "defModifier",
  "mDefModifier",
  "damageBonus",
  "damageReworkBonus",
  "precBonus",
  "rework",
  "qualityCost",
  "totalBonus",
  "selectedQuality",
  "qualityName",
  "isEquipped",
] as const;

const CUSTOM_WEAPON_FIELDS = [
  "itemType",
  "name",
  "description",
  "category",
  "range",
  "hands",
  "martial",
  "accuracy",
  "damage",
  "modifiers",
  "rare",
  "customizations",
  "quality",
  "qualityName",
  "qualityCost",
  "cost",
  "slots",
  "slotted",
  "secondName",
  "secondCategory",
  "secondRange",
  "secondAccuracy",
  "secondDamage",
  "secondModifiers",
  "secondCustomizations",
  "meta",
  "selectedQuality",
  "isEquipped",
  "dataType",
  "passives",
  "behaviors",
] as const;

const ACCESSORY_FIELDS = [
  "itemType",
  "name",
  "quality",
  "qualityCost",
  "selectedQuality",
  "cost",
  "defModifier",
  "mDefModifier",
  "initModifier",
  "magicModifier",
  "precModifier",
  "damageMeleeModifier",
  "damageRangedModifier",
  "modifiers",
  "meta",
  "isEquipped",
] as const;

const SHIELD_FIELDS = [
  "itemType",
  "name",
  "martial",
  "def",
  "mdef",
  "init",
  "rework",
  "quality",
  "qualityCost",
  "selectedQuality",
  "cost",
  "base",
  "defModifier",
  "mDefModifier",
  "initModifier",
  "magicModifier",
  "precModifier",
  "damageMeleeModifier",
  "damageRangedModifier",
  "modifiers",
  "meta",
  "isEquipped",
] as const;

const ARMOR_FIELDS = [
  "itemType",
  "name",
  "martial",
  "def",
  "mdef",
  "init",
  "rework",
  "quality",
  "qualityCost",
  "selectedQuality",
  "cost",
  "base",
  "slots",
  "slotted",
  "isSlotsVariant",
  "defModifier",
  "mDefModifier",
  "initModifier",
  "magicModifier",
  "precModifier",
  "damageMeleeModifier",
  "damageRangedModifier",
  "modifiers",
  "meta",
  "isEquipped",
] as const;

export const ITEM_FIELD_PARITY = {
  weapon: {
    quickCreate: WEAPON_FIELDS,
    create: WEAPON_FIELDS,
    edit: WEAPON_FIELDS,
  },
  customWeapon: {
    quickCreate: CUSTOM_WEAPON_FIELDS,
    create: CUSTOM_WEAPON_FIELDS,
    edit: CUSTOM_WEAPON_FIELDS,
  },
  accessory: {
    quickCreate: ACCESSORY_FIELDS,
    create: ACCESSORY_FIELDS,
    edit: ACCESSORY_FIELDS,
  },
  shield: {
    quickCreate: SHIELD_FIELDS,
    create: SHIELD_FIELDS,
    edit: SHIELD_FIELDS,
  },
  armor: {
    quickCreate: ARMOR_FIELDS,
    create: ARMOR_FIELDS,
    edit: ARMOR_FIELDS,
  },
} satisfies Record<string, SurfaceFieldParity>;
