const armor = [
  {
    fuid: "no-armor",
    category: "Armor",
    name: "No Armor",
    cost: 0,
    def: 0,
    mdef: 0,
    armor: true,
    martial: false,
    init: 0,
    meta: { book: "core", page: "", isOfficial: true },
  },
  {
    fuid: "silk-shirt",
    category: "Armor",
    name: "Silk Shirt",
    cost: 100,
    def: 0,
    mdef: 2,
    armor: true,
    martial: false,
    init: -1,
    meta: { book: "core", page: "", isOfficial: true },
  },
  {
    fuid: "travel-garb",
    category: "Armor",
    name: "Travel Garb",
    cost: 100,
    def: 1,
    mdef: 1,
    armor: true,
    martial: false,
    init: -1,
    meta: { book: "core", page: "", isOfficial: true },
  },
  {
    fuid: "combat-tunic",
    category: "Armor",
    name: "Combat Tunic",
    cost: 150,
    def: 1,
    mdef: 1,
    armor: true,
    martial: false,
    init: 0,
    meta: { book: "core", page: "", isOfficial: true },
  },
  {
    fuid: "sage-robe",
    category: "Armor",
    name: "Combat Tunic (Rework)",
    cost: 150,
    def: 2,
    mdef: 0,
    armor: true,
    martial: false,
    init: 0,
    meta: { book: "core", page: "", isOfficial: true },
  },
  {
    fuid: "sage-robe",
    category: "Armor",
    name: "Sage Robe",
    cost: 200,
    def: 1,
    mdef: 2,
    armor: true,
    martial: false,
    init: -2,
    meta: { book: "core", page: "", isOfficial: true },
  },
  {
    fuid: "brigandine",
    category: "Armor",
    name: "Brigandine",
    cost: 150,
    def: 10,
    mdef: 0,
    armor: true,
    martial: true,
    init: -2,
    meta: { book: "core", page: "", isOfficial: true },
  },
  {
    fuid: "bronze-plate",
    category: "Armor",
    name: "Bronze Plate",
    cost: 200,
    def: 11,
    mdef: 0,
    armor: true,
    martial: true,
    init: -3,
    meta: { book: "core", page: "", isOfficial: true },
  },
  {
    fuid: "runic-plate",
    category: "Armor",
    name: "Runic Plate",
    cost: 250,
    def: 11,
    mdef: 1,
    armor: true,
    martial: true,
    init: -3,
    meta: { book: "core", page: "", isOfficial: true },
  },
  {
    fuid: "steel-plate",
    category: "Armor",
    name: "Steel Plate",
    cost: 300,
    def: 12,
    mdef: 0,
    armor: true,
    martial: true,
    init: -4,
    meta: { book: "core", page: "", isOfficial: true },
  },
];

export default armor;
