const classList = [
  {
    name: "Arcanist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["arcanist"],
    },
  },
  {
    name: "Chimerist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: true,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["default"],
    },
  },
  {
    name: "Darkblade",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: true,
        shields: false,
        melee: true,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  {
    name: "Elementalist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: true,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["default"],
    },
  },
  {
    name: "Entropist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: true,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["default"],
    },
  },
  {
    name: "Fury",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: true,
        shields: false,
        melee: true,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  {
    name: "Guardian",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: true,
        shields: true,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  {
    name: "Loremaster",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  {
    name: "Orator",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  {
    name: "Rogue",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  {
    name: "Sharpshooter",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: true,
        melee: false,
        ranged: true,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  {
    name: "Spiritist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["default"],
    },
  },
  {
    name: "Tinkerer",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [
        "tinkerer-alchemy",
        "tinkerer-infusion",
        "tinkerer-magitech",
      ],
    },
  },
  {
    name: "Wayfarer",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  {
    name: "Weaponmaster",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: true,
        melee: true,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  {
    name: "Arcanist-Rework",
    book: "rework",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["arcanist-rework"],
    },
  },
];


export default classList;