const classes = {
  arcanist: {
    name: "Arcanist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["arcanist"],
    },
  },
  chimerist: {
    name: "Chimerist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: true,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["default"],
    },
  },
  darkblade: {
    name: "Darkblade",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: true,
        shields: false,
        melee: true,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  elementalist: {
    name: "Elementalist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: true,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["default"],
    },
  },
  entropist: {
    name: "Entropist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: true,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["default"],
    },
  },
  fury: {
    name: "Fury",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: true,
        shields: false,
        melee: true,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  guardian: {
    name: "Guardian",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: true,
        shields: true,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  loremaster: {
    name: "Loremaster",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  orator: {
    name: "Orator",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  rogue: {
    name: "Rogue",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  sharpshooter: {
    name: "Sharpshooter",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: true,
        melee: false,
        ranged: true,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  spiritist: {
    name: "Spiritist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: ["default"],
    },
  },
  tinkerer: {
    name: "Tinkerer",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [
        "tinkerer-alchemy",
        "tinkerer-infusion",
        "tinkerer-magitech",
      ],
    },
  },
  wayfarer: {
    name: "Wayfarer",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
  weaponmaster: {
    name: "Weaponmaster",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: true,
        melee: true,
        ranged: false,
      },
      rituals: {
        ritualism: false,
        arcanism: false,
        chimerism: false,
        elementalism: false,
        entropism: false,
        spiritism: false,
      },
      spellClasses: [],
    },
  },
};
