import { t } from "../translation/translate";

const classList = [
  {
    fuid: "arcanist",
    name: "Arcanist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: ["arcanist"],
    },
    skills: [
      {
        skillName: "Arcane Circle",
        currentLvl: 0,
        maxLvl: 4,
        description: "ArcaneCircle_desc",
        specialSkill: "",
      },
      {
        skillName: "Arcane Regeneration",
        currentLvl: 0,
        maxLvl: 2,
        description: "ArcaneRegeneration_desc",
        specialSkill: "",
      },
      {
        skillName: "Bind and Summon",
        currentLvl: 0,
        maxLvl: 1,
        description: "BindAndSummon_desc",
        specialSkill: "",
      },
      {
        skillName: "Emergency Arcanum",
        currentLvl: 0,
        maxLvl: 6,
        description: "EmergencyArcanum_desc",
        specialSkill: "",
      },
      {
        skillName: "Ritual Arcanism",
        currentLvl: 0,
        maxLvl: 1,
        description: "RitualArcanism_desc",
        specialSkill: "Ritual Arcanism",
      },
    ],
  },
  {
    fuid: "chimerist",
    name: "Chimerist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: true,
      },
      spellClasses: ["default"],
    },
    skills: [
      {
        skillName: "Consume",
        currentLvl: 0,
        maxLvl: 5,
        description: "Consume_desc",
        specialSkill: "",
      },
      {
        skillName: "Feral Speech",
        currentLvl: 0,
        maxLvl: 1,
        description: "FeralSpeech_desc",
        specialSkill: "",
      },
      {
        skillName: "Pathogenesis",
        currentLvl: 0,
        maxLvl: 1,
        description: "Pathogenesis_desc",
        specialSkill: "",
      },
      {
        skillName: "Ritual Chimerism",
        currentLvl: 0,
        maxLvl: 1,
        description: "RitualChimerism_desc",
        specialSkill: "Ritual Chimerism",
      },
      {
        skillName: "Spell Mimic",
        currentLvl: 0,
        maxLvl: 10,
        description: "SpellMimic_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "darkblade",
    name: "Darkblade",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: true,
        shields: false,
        melee: true,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Agony",
        currentLvl: 0,
        maxLvl: 5,
        description: "Agony_desc",
        specialSkill: "",
      },
      {
        skillName: "Dark Blood",
        currentLvl: 0,
        maxLvl: 1,
        description: "DarkBlood_desc",
        specialSkill: "",
      },
      {
        skillName: "Heart of Darkness",
        currentLvl: 0,
        maxLvl: 1,
        description: "HeartOfDarkness_desc",
        specialSkill: "",
      },
      {
        skillName: "Painful Lessons",
        currentLvl: 0,
        maxLvl: 3,
        description: "PainfulLessons_desc",
        specialSkill: "",
      },
      {
        skillName: "Shadow Strike",
        currentLvl: 0,
        maxLvl: 5,
        description: "ShadowStrike_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "elementalist",
    name: "Elementalist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: true,
      },
      spellClasses: ["default"],
    },
    skills: [
      {
        skillName: "Cataclysm",
        currentLvl: 0,
        maxLvl: 3,
        description: "Cataclysm_desc",
        specialSkill: "",
      },
      {
        skillName: "Elemental Magic",
        currentLvl: 0,
        maxLvl: 10,
        description: "ElementalMagic_desc",
        specialSkill: "",
      },
      {
        skillName: "Magic Artillery",
        currentLvl: 0,
        maxLvl: 3,
        description: "MagicArtillery_desc",
        specialSkill: "",
      },
      {
        skillName: "Ritual Elementalism",
        currentLvl: 0,
        maxLvl: 1,
        description: "RitualElementalism_desc",
        specialSkill: "Ritual Elementalism",
      },
      {
        skillName: "Spellblade",
        currentLvl: 0,
        maxLvl: 4,
        description: "Spellblade_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "entropist",
    name: "Entropist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: true,
      },
      spellClasses: ["default", "gamble"],
    },
    skills: [
      {
        skillName: "Absorb MP",
        currentLvl: 0,
        maxLvl: 5,
        description: "AbsorbMP_desc",
        specialSkill: "",
      },
      {
        skillName: "Entropic Magic",
        currentLvl: 0,
        maxLvl: 10,
        description: "EntropicMagic_desc",
        specialSkill: "",
      },
      {
        skillName: "Lucky Seven",
        currentLvl: 0,
        maxLvl: 1,
        description: "LuckySeven_desc",
        specialSkill: "",
      },
      {
        skillName: "Ritual Entropism",
        currentLvl: 0,
        maxLvl: 1,
        description: "RitualEntropism_desc",
        specialSkill: "Ritual Entropism",
      },
      {
        skillName: "Stolen Time",
        currentLvl: 0,
        maxLvl: 4,
        description: "StolenTime_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "fury",
    name: "Fury",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: true,
        shields: false,
        melee: true,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Adrenaline",
        currentLvl: 0,
        maxLvl: 5,
        description: "Adrenaline_desc",
        specialSkill: "",
      },
      {
        skillName: "Frenzy",
        currentLvl: 0,
        maxLvl: 1,
        description: "Frenzy_desc",
        specialSkill: "",
      },
      {
        skillName: "Indomitable Spirit",
        currentLvl: 0,
        maxLvl: 4,
        description: "IndomitableSpirit_desc",
        specialSkill: "",
      },
      {
        skillName: "Provoke",
        currentLvl: 0,
        maxLvl: 5,
        description: "Provoke_desc",
        specialSkill: "",
      },
      {
        skillName: "Withstand",
        currentLvl: 0,
        maxLvl: 5,
        description: "Withstand_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "guardian",
    name: "Guardian",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: true,
        shields: true,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Bodyguard",
        currentLvl: 0,
        maxLvl: 1,
        description: "Bodyguard_desc",
        specialSkill: "",
      },
      {
        skillName: "Defensive Mastery",
        currentLvl: 0,
        maxLvl: 5,
        description: "DefensiveMastery_desc",
        specialSkill: "Defensive Mastery",
      },
      {
        skillName: "Dual Shieldbearer",
        currentLvl: 0,
        maxLvl: 1,
        description: "DualShieldbearer_desc",
        specialSkill: "Dual Shieldbearer",
      },
      {
        skillName: "Fortress",
        currentLvl: 0,
        maxLvl: 5,
        description: "Fortress_desc",
        specialSkill: "Fortress",
      },
      {
        skillName: "Protect",
        currentLvl: 0,
        maxLvl: 1,
        description: "Protect_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "loremaster",
    name: "Loremaster",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Flash of Insight",
        currentLvl: 0,
        maxLvl: 3,
        description: "FlashOfInsight_desc",
        specialSkill: "",
      },
      {
        skillName: "Focused",
        currentLvl: 0,
        maxLvl: 5,
        description: "Focused_desc",
        specialSkill: "Focused",
      },
      {
        skillName: "Knowledge Is Power",
        currentLvl: 0,
        maxLvl: 1,
        description: "KnowledgeIsPower_desc",
        specialSkill: "",
      },
      {
        skillName: "Quick Assessment",
        currentLvl: 0,
        maxLvl: 6,
        description: "QuickAssessment_desc",
        specialSkill: "",
      },
      {
        skillName: "Trained Memory",
        currentLvl: 0,
        maxLvl: 1,
        description: "TrainedMemory_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "orator",
    name: "Orator",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Condemn",
        currentLvl: 0,
        maxLvl: 6,
        description: "Condemn_desc",
        specialSkill: "",
      },
      {
        skillName: "Encourage",
        currentLvl: 0,
        maxLvl: 6,
        description: "Encourage_desc",
        specialSkill: "",
      },
      {
        skillName: "My Trust In You",
        currentLvl: 0,
        maxLvl: 2,
        description: "MyTrustInYou_desc",
        specialSkill: "",
      },
      {
        skillName: "Persuasive",
        currentLvl: 0,
        maxLvl: 2,
        description: "Persuasive_desc",
        specialSkill: "",
      },
      {
        skillName: "Unexpected Ally",
        currentLvl: 0,
        maxLvl: 1,
        description: "UnexpectedAlly_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "rogue",
    name: "Rogue",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Cheap Shot",
        currentLvl: 0,
        maxLvl: 5,
        description: "CheapShot_desc",
        specialSkill: "",
      },
      {
        skillName: "Dodge",
        currentLvl: 0,
        maxLvl: 3,
        description: "Dodge_desc",
        specialSkill: "Dodge",
      },
      {
        skillName: "High Speed",
        currentLvl: 0,
        maxLvl: 3,
        description: "HighSpeed_desc",
        specialSkill: "",
      },
      {
        skillName: "See You Later",
        currentLvl: 0,
        maxLvl: 1,
        description: "SeeYouLater_desc",
        specialSkill: "",
      },
      {
        skillName: "Soul Steal",
        currentLvl: 0,
        maxLvl: 5,
        description: "SoulSteal_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "sharpshooter",
    name: "Sharpshooter",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: true,
        melee: false,
        ranged: true,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Barrage",
        currentLvl: 0,
        maxLvl: 1,
        description: "Barrage_desc",
        specialSkill: "",
      },
      {
        skillName: "Crossfire",
        currentLvl: 0,
        maxLvl: 1,
        description: "Crossfire_desc",
        specialSkill: "",
      },
      {
        skillName: "Hawkeye",
        currentLvl: 0,
        maxLvl: 5,
        description: "Hawkeye_desc",
        specialSkill: "",
      },
      {
        skillName: "Ranged Weapon Mastery",
        currentLvl: 0,
        maxLvl: 4,
        description: "RangedWeaponMastery_desc",
        specialSkill: "Ranged Weapon Mastery",
      },
      {
        skillName: "Warning Shot",
        currentLvl: 0,
        maxLvl: 4,
        description: "WarningShot_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "spiritist",
    name: "Spiritist",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: ["default"],
    },
    skills: [
      {
        skillName: "Healing Power",
        currentLvl: 0,
        maxLvl: 2,
        description: "HealingPower_desc",
        specialSkill: "",
      },
      {
        skillName: "Ritual Spiritism",
        currentLvl: 0,
        maxLvl: 1,
        description: "RitualSpiritism_desc",
        specialSkill: "Ritual Spiritism",
      },
      {
        skillName: "Spiritual Magic",
        currentLvl: 0,
        maxLvl: 10,
        description: "SpiritualMagic_desc",
        specialSkill: "",
      },
      {
        skillName: "Support Magic",
        currentLvl: 0,
        maxLvl: 1,
        description: "SupportMagic_desc",
        specialSkill: "",
      },
      {
        skillName: "Vismagus",
        currentLvl: 0,
        maxLvl: 1,
        description: "Vismagus_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "tinkerer",
    name: "Tinkerer",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [
        "tinkerer-alchemy",
        "tinkerer-infusion",
        "tinkerer-magitech",
        "default",
      ],
    },
    skills: [
      {
        skillName: "Emergency Item",
        currentLvl: 0,
        maxLvl: 1,
        description: "EmergencyItem_desc",
        specialSkill: "",
      },
      {
        skillName: "Gadgets",
        currentLvl: 0,
        maxLvl: 5,
        description: "Gadgets_desc",
        specialSkill: "",
      },
      {
        skillName: "Potion Rain",
        currentLvl: 0,
        maxLvl: 2,
        description: "PotionRain_desc",
        specialSkill: "",
      },
      {
        skillName: "Secret Formula",
        currentLvl: 0,
        maxLvl: 5,
        description: "SecretFormula_desc",
        specialSkill: "",
      },
      {
        skillName: "Visionary",
        currentLvl: 0,
        maxLvl: 5,
        description: "Visionary_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "wayfarer",
    name: "Wayfarer",
    book: "core",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Faithful Companion",
        currentLvl: 0,
        maxLvl: 5,
        description: "FaithfulCompanion_desc",
        specialSkill: "Faithful Companion",
      },
      {
        skillName: "Resourceful",
        currentLvl: 0,
        maxLvl: 4,
        description: "Resourceful_desc",
        specialSkill: "",
      },
      {
        skillName: "Tavern Talk",
        currentLvl: 0,
        maxLvl: 3,
        description: "TavernTalk_desc",
        specialSkill: "",
      },
      {
        skillName: "Treasure Hunter",
        currentLvl: 0,
        maxLvl: 2,
        description: "TreasureHunter_desc",
        specialSkill: "",
      },
      {
        skillName: "Well-Traveled",
        currentLvl: 0,
        maxLvl: 1,
        description: "WellTraveled_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "weaponmaster",
    name: "Weaponmaster",
    book: "core",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: true,
        melee: true,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Bladestorm",
        currentLvl: 0,
        maxLvl: 1,
        description: "Bladestorm_desc",
        specialSkill: "",
      },
      {
        skillName: "Bone Crusher",
        currentLvl: 0,
        maxLvl: 4,
        description: "BoneCrusher_desc",
        specialSkill: "",
      },
      {
        skillName: "Breach",
        currentLvl: 0,
        maxLvl: 3,
        description: "Breach_desc",
        specialSkill: "",
      },
      {
        skillName: "Counterattack",
        currentLvl: 0,
        maxLvl: 1,
        description: "Counterattack_desc",
        specialSkill: "",
      },
      {
        skillName: "Melee Weapon Mastery",
        currentLvl: 0,
        maxLvl: 4,
        description: "MeleeWeaponMastery_desc",
        specialSkill: "Melee Weapon Mastery",
      },
    ],
  },
  {
    fuid: "arcanist-rework",
    name: "Arcanist-Rework",
    book: "rework",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: ["arcanist-rework"],
    },
    skills: [],
  },
  {
    fuid: "ace-of-cards",
    name: "Ace of Cards",
    book: "bonus",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: true,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      custom: [
        "You may choose to permanently increase your maximum Hit Points or Mind Points by 5 (your choice).",
      ],
      spellClasses: ["deck"],
    },
    skills: [
      {
        skillName: "Double or Nothing",
        currentLvl: 0,
        maxLvl: 1,
        description: "DoubleOrNothing_desc",
        specialSkill: "",
      },
      {
        skillName: "High or Low",
        currentLvl: 0,
        maxLvl: 1,
        description: "HighOrLow_desc",
        specialSkill: "",
      },
      {
        skillName: "Magic Cards",
        currentLvl: 0,
        maxLvl: 3,
        description: "MagicCards_desc",
        specialSkill: "",
      },
      {
        skillName: "Mulligan",
        currentLvl: 0,
        maxLvl: 5,
        description: "Mulligan_desc",
        specialSkill: "",
      },
      {
        skillName: "Trap Card",
        currentLvl: 0,
        maxLvl: 4,
        description: "TrapCard_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "necromancer",
    name: "Necromancer",
    book: "bonus",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: true,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      custom: [
        "You may choose to permanently increase your maximum Hit Points or Mind Points by 5 (your choice).",
      ],
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Beyond The Realms Of Death",
        currentLvl: 0,
        maxLvl: 5,
        description: "BeyondTheRealmsOfDeath_desc",
        specialSkill: "",
      },
      {
        skillName: "Children Of The Grave",
        currentLvl: 0,
        maxLvl: 1,
        description: "ChildrenOfTheGrave_desc",
        specialSkill: "",
      },
      {
        skillName: "Fear Is The Key",
        currentLvl: 0,
        maxLvl: 3,
        description: "FearIsTheKey_desc",
        specialSkill: "",
      },
      {
        skillName: "For Whom The Bell Tolls",
        currentLvl: 0,
        maxLvl: 3,
        description: "ForWhomTheBellTolls_desc",
        specialSkill: "",
      },
      {
        skillName: "Rondo Of Nightmare",
        currentLvl: 0,
        maxLvl: 1,
        description: "RondoOfNightmare_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "chanter",
    name: "Chanter",
    book: "high",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: ["magichant"],
    },
    skills: [
      {
        skillName: "Magichant",
        currentLvl: 0,
        maxLvl: 10,
        description: "Magichant_desc",
        specialSkill: "",
      },
      {
        skillName: "Resonance",
        currentLvl: 0,
        maxLvl: 3,
        description: "Resonance_desc",
        specialSkill: "",
      },
      {
        skillName: "Siren's Song",
        currentLvl: 0,
        maxLvl: 1,
        description: "SirensSong_desc",
        specialSkill: "",
      },
      {
        skillName: "Sound Barrier",
        currentLvl: 0,
        maxLvl: 5,
        description: "SoundBarrier_desc",
        specialSkill: "",
      },
      {
        skillName: "Vibrato",
        currentLvl: 0,
        maxLvl: 1,
        description: "Vibrato_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "commander",
    name: "Commander",
    book: "high",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: true,
        ranged: true,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "Bishop's Edict",
        currentLvl: 0,
        maxLvl: 5,
        description: "BishopsEdict_desc",
        specialSkill: "",
      },
      {
        skillName: "Charging Cavalry",
        currentLvl: 0,
        maxLvl: 5,
        description: "ChargingCavalry_desc",
        specialSkill: "",
      },
      {
        skillName: "Crushing Chariot",
        currentLvl: 0,
        maxLvl: 1,
        description: "CrushingChariot_desc",
        specialSkill: "",
      },
      {
        skillName: "King's Castle",
        currentLvl: 0,
        maxLvl: 4,
        description: "KingsCastle_desc",
        specialSkill: "",
      },
      {
        skillName: "Queen's Gambit",
        currentLvl: 0,
        maxLvl: 6,
        description: "QueensGambit_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "dancer",
    name: "Dancer",
    book: "high",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: true,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      custom: [
        "You may choose to permanently increase your maximum Hit Points or Mind Points by 5 (your choice).",
      ],
      spellClasses: ["dance"],
    },
    skills: [
      {
        skillName: "Dance",
        currentLvl: 0,
        maxLvl: 10,
        description: "Dance_desc",
        specialSkill: "",
      },
      {
        skillName: "Follow My Lead",
        currentLvl: 0,
        maxLvl: 1,
        description: "FollowMyLead_desc",
        specialSkill: "",
      },
      {
        skillName: "Frenetic Footwork",
        currentLvl: 0,
        maxLvl: 2,
        description: "FreneticFootwork_desc",
        specialSkill: "",
      },
      {
        skillName: "Quick-Change",
        currentLvl: 0,
        maxLvl: 1,
        description: "QuickChange_desc",
        specialSkill: "",
      },
      {
        skillName: "Wardancer",
        currentLvl: 0,
        maxLvl: 5,
        description: "Wardancer_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "symbolist",
    name: "Symbolist",
    book: "high",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: ["symbol"],
    },
    skills: [
      {
        skillName: "Magic Symbols",
        currentLvl: 0,
        maxLvl: 3,
        description: "MagicSymbols_desc",
        specialSkill: "",
      },
      {
        skillName: "Mirage",
        currentLvl: 0,
        maxLvl: 1,
        description: "Mirage_desc",
        specialSkill: "",
      },
      {
        skillName: "Personal Touch",
        currentLvl: 0,
        maxLvl: 5,
        description: "PersonalTouch_desc",
        specialSkill: "",
      },
      {
        skillName: "Symbolic Connection",
        currentLvl: 0,
        maxLvl: 1,
        description: "SymbolicConnection_desc",
        specialSkill: "",
      },
      {
        skillName: "Symbolism",
        currentLvl: 0,
        maxLvl: 5,
        description: "Symbolism_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "esper",
    name: "Esper",
    book: "techno",
    benefits: {
      hpplus: 0,
      mpplus: 5,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },

      spellClasses: ["gift"],
    },
    skills: [
      {
        skillName: "Cognitive Focus",
        currentLvl: 0,
        maxLvl: 5,
        description: "CognitiveFocus_desc",
        specialSkill: "",
      },
      {
        skillName: "Hypercognition",
        currentLvl: 0,
        maxLvl: 5,
        description: "Hypercognition_desc",
        specialSkill: "",
      },
      {
        skillName: "Navigator",
        currentLvl: 0,
        maxLvl: 1,
        description: "Navigator_desc",
        specialSkill: "",
      },
      {
        skillName: "Psychic Gifts",
        currentLvl: 0,
        maxLvl: 5,
        description: "PsychicGifts_desc",
        specialSkill: "",
      },
      {
        skillName: "Psychokinesis",
        currentLvl: 0,
        maxLvl: 1,
        description: "Psychokinesis_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "mutant",
    name: "Mutant",
    book: "techno",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: ["therioform"],
    },
    skills: [
      {
        skillName: "Akromorphosis",
        currentLvl: 0,
        maxLvl: 3,
        description: "Akromorphosis_desc",
        specialSkill: "",
      },
      {
        skillName: "Biophagy",
        currentLvl: 0,
        maxLvl: 4,
        description: "Biophagy_desc",
        specialSkill: "",
      },
      {
        skillName: "Ecdysis",
        currentLvl: 0,
        maxLvl: 1,
        description: "Ecdysis_desc",
        specialSkill: "",
      },
      {
        skillName: "Genoclepsis",
        currentLvl: 0,
        maxLvl: 2,
        description: "Genoclepsis_desc",
        specialSkill: "",
      },
      {
        skillName: "Theriomorphosis",
        currentLvl: 0,
        maxLvl: 6,
        description: "Theriomorphosis_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "pilot",
    name: "Pilot",
    book: "techno",
    benefits: {
      hpplus: 5,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: true,
        ranged: true,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: ["pilot-vehicle"],
    },
    skills: [
      {
        skillName: "Compression Tech",
        currentLvl: 0,
        maxLvl: 1,
        description: "CompressionTech_desc",
        specialSkill: "",
      },
      {
        skillName: "Flexible Configuration",
        currentLvl: 0,
        maxLvl: 4,
        description: "FlexibleConfiguration_desc",
        specialSkill: "",
      },
      {
        skillName: "Heart in the Engine",
        currentLvl: 0,
        maxLvl: 3,
        description: "HeartInTheEngine_desc",
        specialSkill: "",
      },
      {
        skillName: "Personal Vehicle",
        currentLvl: 0,
        maxLvl: 5,
        description: "PersonalVehicle_desc",
        specialSkill: "",
      },
      {
        skillName: "Strong Grip",
        currentLvl: 0,
        maxLvl: 1,
        description: "StrongGrip_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "floralist",
    name: "Floralist",
    book: "natural",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: true,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      custom: [
        "You may choose to permanently increase your maximum Hit Points or Mind Points by 5 (your choice).",
      ],
      spellClasses: ["magiseed"],
    },
    skills: [
      {
        skillName: "BattleGardening",
        currentLvl: 0,
        maxLvl: 3,
        description: "BattleGardening_desc",
        specialSkill: "",
      },
      {
        skillName: "Chloromancy",
        currentLvl: 0,
        maxLvl: 10,
        description: "Chloromancy_desc",
        specialSkill: "",
      },
      {
        skillName: "Graft",
        currentLvl: 0,
        maxLvl: 1,
        description: "Graft_desc",
        specialSkill: "",
      },
      {
        skillName: "TreeOfLife",
        currentLvl: 0,
        maxLvl: 5,
        description: "TreeOfLife_desc",
        specialSkill: "",
      },
      {
        skillName: "VerdantSway",
        currentLvl: 0,
        maxLvl: 1,
        description: "VerdantSway_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "gourmet",
    name: "Gourmet",
    book: "natural",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: true,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      custom: [
        "You may start Projects to create unique foods and drinks; they are always consumable and their area is based on the number and type of creatures you need to nourish.",
      ],
      spellClasses: ["cooking"],
    },
    skills: [
      {
        skillName: "Cooking",
        currentLvl: 0,
        maxLvl: 5,
        description: "Cooking_desc",
        specialSkill: "",
      },
      {
        skillName: "KnifeAndFork",
        currentLvl: 0,
        maxLvl: 1,
        description: "KnifeAndFork_desc",
        specialSkill: "",
      },
      {
        skillName: "MadeWithLove",
        currentLvl: 0,
        maxLvl: 3,
        description: "MadeWithLove_desc",
        specialSkill: "",
      },
      {
        skillName: "SaltAndPepper",
        currentLvl: 0,
        maxLvl: 1,
        description: "SaltAndPepper_desc",
        specialSkill: "",
      },
      {
        skillName: "TravelingCook",
        currentLvl: 0,
        maxLvl: 3,
        description: "TravelingCook_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "invoker",
    name: "Invoker",
    book: "natural",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: true,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      custom: [
        "You may choose to permanently increase your maximum Hit Points or Mind Points by 5 (your choice).",
      ],
      spellClasses: ["invocation"],
    },
    skills: [
      {
        skillName: "ElementalHarmony",
        currentLvl: 0,
        maxLvl: 2,
        description: "ElementalHarmony_desc",
        specialSkill: "",
      },
      {
        skillName: "Invocation",
        currentLvl: 0,
        maxLvl: 3,
        description: "Invocation_desc",
        specialSkill: "",
      },
      {
        skillName: "LinkedInvocation",
        currentLvl: 0,
        maxLvl: 3,
        description: "LinkedInvocation_desc",
        specialSkill: "",
      },
      {
        skillName: "Ripples",
        currentLvl: 0,
        maxLvl: 5,
        description: "Ripples_desc",
        specialSkill: "",
      },
      {
        skillName: "WellspringExpansion",
        currentLvl: 0,
        maxLvl: 5,
        description: "WellspringExpansion_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "merchant",
    name: "Merchant",
    book: "natural",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 2,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: [],
    },
    skills: [
      {
        skillName: "ExpirationDate",
        currentLvl: 0,
        maxLvl: 3,
        description: "ExpirationDate_desc",
        specialSkill: "",
      },
      {
        skillName: "IveHeardOfIt",
        currentLvl: 0,
        maxLvl: 3,
        description: "IveHeardOfIt_desc",
        specialSkill: "",
      },
      {
        skillName: "PrivateStock",
        currentLvl: 0,
        maxLvl: 3,
        description: "PrivateStock_desc",
        specialSkill: "",
      },
      {
        skillName: "RealTreasure",
        currentLvl: 0,
        maxLvl: 3,
        description: "RealTreasure_desc",
        specialSkill: "",
      },
      {
        skillName: "WindsOfTrade",
        currentLvl: 0,
        maxLvl: 3,
        description: "WindsOfTrade_desc",
        specialSkill: "",
      },
    ],
  },
  {
    fuid: "blank-class",
    name: "Blank Class",
    book: "homebrew",
    benefits: {
      hpplus: 0,
      mpplus: 0,
      ipplus: 0,
      isCustomBenefit: false,
      martials: {
        armor: false,
        shields: false,
        melee: false,
        ranged: false,
      },
      rituals: {
        ritualism: false,
      },
      spellClasses: ["default"],
    },
    skills: [],
  },
];

export const tinkererAlchemy = {
  spellType: "tinkerer-alchemy",
  rank: 1,
  targets: [
    {
      rangeFrom: 1,
      rangeTo: 6,
      effect: t("You or one ally you can see that is present on the scene"),
    },
    {
      rangeFrom: 7,
      rangeTo: 11,
      effect: t("One enemy you can see that is present on the scene"),
    },
    {
      rangeFrom: 12,
      rangeTo: 16,
      effect: t("You and every ally present on the scene"),
    },
    {
      rangeFrom: 17,
      rangeTo: 20,
      effect: t("Every enemy present on the scene"),
    },
  ],
  effects: [
    {
      dieValue: 0,
      effect: t("is dealt 20 poison damage"),
    },
    {
      dieValue: 0,
      effect: t("recovers 30 Hit Points"),
    },
    {
      dieValue: 1,
      effect: t(
        "treats their Dexterity and Might dice as if they were one size higher (up to a maximum of d12) until the end of your next turn",
      ),
    },
    {
      dieValue: 2,
      effect: t(
        "treats their Insight and Willpower dice as if they were one size higher (up to a maximum of d12) until the end of your next turn",
      ),
    },
    {
      dieValue: 3,
      effect: t(
        "suffers 20 air damage. This amount increases to 30 damage if you are level 20 or higher, or to 40 damage if you are level 40 or higher",
      ),
    },
    {
      dieValue: 4,
      effect: t(
        "suffers 20 bolt damage. This amount increases to 30 damage if you are level 20 or higher, or to 40 damage if you are level 40 or higher",
      ),
    },
    {
      dieValue: 5,
      effect: t(
        "suffers 20 dark damage. This amount increases to 30 damage if you are level 20 or higher, or to 40 damage if you are level 40 or higher",
      ),
    },
    {
      dieValue: 6,
      effect: t(
        "suffers 20 earth damage. This amount increases to 30 damage if you are level 20 or higher, or to 40 damage if you are level 40 or higher",
      ),
    },
    {
      dieValue: 7,
      effect: t(
        "suffers 20 fire damage. This amount increases to 30 damage if you are level 20 or higher, or to 40 damage if you are level 40 or higher",
      ),
    },
    {
      dieValue: 8,
      effect: t(
        "suffers 20 ice damage. This amount increases to 30 damage if you are level 20 or higher, or to 40 damage if you are level 40 or higher",
      ),
    },
    {
      dieValue: 9,
      effect: t(
        "gains Resistance to air and fire damage until the end of the scene",
      ),
    },
    {
      dieValue: 10,
      effect: t(
        "gains Resistance to bolt and ice damage until the end of the scene",
      ),
    },
    {
      dieValue: 11,
      effect: t(
        "gains Resistance to dark and earth damage until the end of the scene",
      ),
    },
    {
      dieValue: 12,
      effect: t("suffers enraged"),
    },
    {
      dieValue: 13,
      effect: t("suffers poisoned"),
    },
    {
      dieValue: 14,
      effect: t("suffers dazed, shaken, slow and weak"),
    },
    {
      dieValue: 15,
      effect: t("recovers from all status effects"),
    },
    {
      dieValue: 16,
      effect: t("recovers 50 Hit Points and 50 Mind Points"),
    },
    {
      dieValue: 17,
      effect: t("recovers 50 Hit Points and 50 Mind Points"),
    },
    {
      dieValue: 18,
      effect: t("recovers 100 Hit Points"),
    },
    {
      dieValue: 19,
      effect: t("recovers 100 Mind Points"),
    },
    {
      dieValue: 20,
      effect: t("recovers 100 Hit Points and 100 Mind Points"),
    },
  ],
};

export const tinkererInfusion = {
  spellType: "tinkerer-infusion",
  rank: 1,
  effects: [
    {
      infusionRank: 1,
      name: t("Cryo"),
      effect: t(
        "The attack deals 5 extra damage, and its damage becomes **ice**.",
      ),
    },
    {
      infusionRank: 1,
      name: t("Pyro"),
      effect: t(
        "The attack deals 5 extra damage, and its damage becomes **fire**.",
      ),
    },
    {
      infusionRank: 1,
      name: t("Volt"),
      effect: t(
        "The attack deals 5 extra damage, and its damage becomes **bolt**.",
      ),
    },
    {
      infusionRank: 2,
      name: t("Cyclone"),
      effect: t(
        "The attack deals 5 extra damage, and its damage becomes **air**.",
      ),
    },
    {
      infusionRank: 2,
      name: t("Exorcism"),
      effect: t(
        "The attack deals 5 extra damage, and its damage becomes **light**.",
      ),
    },
    {
      infusionRank: 2,
      name: t("Seismic"),
      effect: t(
        "The attack deals 5 extra damage, and its damage becomes **earth**.",
      ),
    },
    {
      infusionRank: 2,
      name: t("Shadow"),
      effect: t(
        "The attack deals 5 extra damage, and its damage becomes **dark**.",
      ),
    },
    {
      infusionRank: 3,
      name: t("Vampire"),
      effect: t(
        "Choose one option: you recover an amount of HP equal to half the HP loss suffered by the target of the attack; **or** you recover an amount of MP equal to half the HP loss suffered by the target of the attack. This infusion can only be used if the attack targeted **a single** creature.",
      ),
    },
    {
      infusionRank: 3,
      name: t("Venom"),
      effect: t(
        "The attack deals 5 extra damage, its damage becomes **poison**, and each creature hit by the attack suffers **poisoned**.",
      ),
    },
  ],
};

export const spellList = [
  {
    fuid: "boulder",
    class: "Elementalist",
    name: "Boulder",
    description: "Boulder_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 20, type: "earth", hrZero: false },
  },
  {
    fuid: "elemental-shroud",
    class: "Elementalist",
    name: "Elemental Shroud",
    description: "ElementalShroud_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "elemental-weapon",
    class: "Elementalist",
    name: "Elemental Weapon",
    description: "ElementalWeapon_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: "One equipped weapon",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "flares",
    class: "Elementalist",
    name: "Flare",
    description: "Flare_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 25, type: "fire", hrZero: false },
  },
  {
    fuid: "fulgur",
    class: "Elementalist",
    name: "Fulgur",
    description: "Fulgur_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 15, type: "bolt", hrZero: false },
  },
  {
    fuid: "glacies",
    class: "Elementalist",
    name: "Glacies",
    description: "Glacies_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 15, type: "ice", hrZero: false },
  },
  {
    fuid: "iceberg",
    class: "Elementalist",
    name: "Iceberg",
    description: "Iceberg_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 25, type: "ice", hrZero: false },
  },
  {
    fuid: "ignis",
    class: "Elementalist",
    name: "Ignis",
    description: "Ignis_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 15, type: "fire", hrZero: false },
  },
  {
    fuid: "soaring-strike",
    class: "Elementalist",
    name: "Soaring Strike",
    description: "SoaringStrike_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 1,
    targetDescription: "Self",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "terra",
    class: "Elementalist",
    name: "Terra",
    description: "Terra_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 15, type: "earth", hrZero: false },
  },
  {
    fuid: "thunderbolt",
    class: "Elementalist",
    name: "Thunderbolt",
    description: "Thunderbolt_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 25, type: "bolt", hrZero: false },
  },
  {
    fuid: "ventus",
    class: "Elementalist",
    name: "Ventus",
    description: "Ventus_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 15, type: "air", hrZero: false },
  },
  {
    fuid: "vortex",
    class: "Elementalist",
    name: "Vortex",
    description: "Vortex_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: "Self",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 25, type: "air", hrZero: false },
  },
  {
    fuid: "acceleration",
    class: "Entropist",
    name: "Acceleration",
    description: "Acceleration_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "anomaly",
    class: "Entropist",
    name: "Anomaly",
    description: "Anomaly_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "dark-weapon",
    class: "Entropist",
    name: "Dark Weapon",
    description: "DarkWeapon_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 1,
    targetDescription: "One equipped weapon",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "dispel",
    class: "Entropist",
    name: "Dispel",
    description: "Dispel_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "divination",
    class: "Entropist",
    name: "Divination",
    description: "Divination_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 1,
    targetDescription: "Self",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "drain-spirit",
    class: "Entropist",
    name: "Drain Spirit",
    description: "DrainSpirit_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 5, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 20, type: "untyped", hrZero: false },
  },
  {
    fuid: "drain-vigor",
    class: "Entropist",
    name: "Drain Vigor",
    description: "DrainVigor_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 15, type: "dark", hrZero: false },
  },
  {
    fuid: "mirror",
    class: "Entropist",
    name: "Mirror",
    description: "Mirror_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "omega",
    class: "Entropist",
    name: "Omega",
    description: "Omega_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 15, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 20, type: "untyped", hrZero: false },
  },
  {
    fuid: "stop",
    class: "Entropist",
    name: "Stop",
    description: "Stop_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "umbra",
    class: "Entropist",
    name: "Umbra",
    description: "Umbra_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 15, type: "dark", hrZero: false },
  },
  {
    fuid: "gamble",
    class: "Entropist",
    spellType: "gamble",
    name: "Gamble",
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 2,
    targetDescription: "Special",
    duration: "Instantaneous",
    attr: "will",
    targets: [
      {
        rangeFrom: 1,
        rangeTo: 1,
        effect: t("GambleEffect1"),
        secondRoll: false,
        secondEffects: [],
      },
      {
        rangeFrom: 2,
        rangeTo: 3,
        effect: t("GambleEffect2"),
        secondRoll: false,
        secondEffects: [],
      },
      {
        rangeFrom: 4,
        rangeTo: 6,
        effect: t("GambleEffect3"),
        secondRoll: false,
        secondEffects: [],
      },
      {
        rangeFrom: 7,
        rangeTo: 8,
        effect: t("GambleEffect4"),
        secondRoll: false,
        secondEffects: [],
      },
      {
        rangeFrom: 9,
        rangeTo: 12,
        effect: t("GambleEffect5"),
        secondRoll: true,
        secondEffects: [
          {
            dieValue: 1,
            effect: t("wind"),
          },
          {
            dieValue: 2,
            effect: t("bolt"),
          },
          {
            dieValue: 3,
            effect: t("dark"),
          },
          {
            dieValue: 4,
            effect: t("earth"),
          },
          {
            dieValue: 5,
            effect: t("fire"),
          },
          {
            dieValue: 6,
            effect: t("poison"),
          },
        ],
      },
    ],
  },
  {
    fuid: "elemental-shroud",
    class: "Spiritist",
    name: "Aura",
    description: "Aura_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "awaken",
    class: "Spiritist",
    name: "Awaken",
    description: "Awaken_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "barrier",
    class: "Spiritist",
    name: "Barrier",
    description: "Barrier_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "cleanse",
    class: "Spiritist",
    name: "Cleanse",
    description: "Cleanse_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "enrage",
    class: "Spiritist",
    name: "Enrage",
    description: "Enrage_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "hallucination",
    class: "Spiritist",
    name: "Hallucination",
    description: "Hallucination_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "heal",
    class: "Spiritist",
    name: "Heal",
    description: "Heal_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "lux",
    class: "Spiritist",
    name: "Lux",
    description: "Lux_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 15, type: "light", hrZero: false },
  },
  {
    fuid: "mercy",
    class: "Spiritist",
    name: "Mercy",
    description: "Mercy_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 1,
    targetDescription: "One creature",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "reinforce",
    class: "Spiritist",
    name: "Reinforce",
    description: "Reinforce_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "soul-shroud",
    class: "Spiritist",
    name: "Soul Shroud",
    description: "SoulShroud_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "soul-weapon",
    class: "Spiritist",
    name: "Soul Weapon",
    description: "SoulWeapon_desc",
    isOffensive: false,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 1,
    targetDescription: "One equipped weapon",
    duration: "Scene",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
  {
    fuid: "torpor",
    class: "Spiritist",
    name: "Torpor",
    description: "Torpor_desc",
    isOffensive: true,
    cost: { resource: "mp", amount: 5, perTarget: true },
    maxTargets: 3,
    targetDescription: "Up to three creatures",
    duration: "Instantaneous",
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    spellType: "default",
    range: "ranged",
    itemType: "spell",
    special: [],
    damage: { value: 0, type: "physical", hrZero: false },
  },
];

// Memoized spell index by class O(1) lookup
export const spellsByClass = spellList.reduce((acc, spell) => {
  if (!acc[spell.class]) acc[spell.class] = [];
  acc[spell.class].push(spell);
  return acc;
}, {});

export const arcanumList = [
  {
    fuid: "arcanum-of-the-forge",
    name: "Arcanum of the Forge",
    description: "",
    domain: "",
    spellType: "arcanist",
    domainDesc: "Arcanum_of_the_Forge_domains",
    index: 0,
    dismiss: "",
    dismissDesc: "Arcanum_of_the_Forge_dismiss",
    showInPlayerSheet: true,
    merge: "",
    mergeDesc: "Arcanum_of_the_Forge_merge",
  },
  {
    fuid: "arcanum-of-the-frost",
    name: "Arcanum of the Frost",
    description: "",
    domain: "",
    spellType: "arcanist",
    domainDesc: "Arcanum_of_the_Frost_domains",
    index: 1,
    dismiss: "",
    dismissDesc: "Arcanum_of_the_Frost_dismiss",
    showInPlayerSheet: true,
    merge: "",
    mergeDesc: "Arcanum_of_the_Frost_merge",
  },
  {
    fuid: "arcanum-of-the-gate",
    name: "Arcanum of the Gate",
    description: "",
    domain: "",
    spellType: "arcanist",
    domainDesc: "Arcanum_of_the_Gate_domains",
    index: 2,
    dismiss: "",
    dismissDesc: "Arcanum_of_the_Gate_dismiss",
    showInPlayerSheet: true,
    merge: "",
    mergeDesc: "Arcanum_of_the_Gate_merge",
  },
  {
    fuid: "arcanum-of-the-grimoire",
    name: "Arcanum of the Grimoire",
    description: "",
    domain: "",
    spellType: "arcanist",
    domainDesc: "Arcanum_of_the_Grimoire_domains",
    index: 3,
    dismiss: "",
    dismissDesc: "Arcanum_of_the_Grimoire_dismiss",
    showInPlayerSheet: true,
    merge: "",
    mergeDesc: "Arcanum_of_the_Grimoire_merge",
  },
  {
    fuid: "arcanum-of-the-oak",
    name: "Arcanum of the Oak",
    description: "",
    domain: "",
    spellType: "arcanist",
    domainDesc: "Arcanum_of_the_Oak_domains",
    index: 4,
    dismiss: "",
    dismissDesc: "Arcanum_of_the_Oak_dismiss",
    showInPlayerSheet: true,
    merge: "",
    mergeDesc: "Arcanum_of_the_Oak_merge",
  },
  {
    fuid: "arcanum-of-the-sky",
    name: "Arcanum of the Sky",
    description: "",
    domain: "",
    spellType: "arcanist",
    domainDesc: "Arcanum_of_the_Sky_domains",
    index: 5,
    dismiss: "",
    dismissDesc: "Arcanum_of_the_Sky_dismiss",
    showInPlayerSheet: true,
    merge: "",
    mergeDesc: "Arcanum_of_the_Sky_merge",
  },
  {
    fuid: "arcanum-of-the-sword",
    name: "Arcanum of the Sword",
    description: "",
    domain: "",
    spellType: "arcanist",
    domainDesc: "Arcanum_of_the_Sword_domains",
    index: 6,
    dismiss: "",
    dismissDesc: "",
    showInPlayerSheet: true,
    merge: "",
    mergeDesc: "Arcanum_of_the_Sword_merge",
  },
  {
    fuid: "arcanum-of-the-tower",
    name: "Arcanum of the Tower",
    description: "",
    domain: "",
    spellType: "arcanist",
    domainDesc: "Arcanum_of_the_Tower_domains",
    index: 7,
    dismiss: "",
    dismissDesc: "Arcanum_of_the_Tower_dismiss",
    showInPlayerSheet: true,
    merge: "",
    mergeDesc: "Arcanum_of_the_Tower_merge",
  },
  {
    fuid: "arcanum-of-the-wheels",
    name: "Arcanum of the Wheel",
    description: "",
    domain: "",
    spellType: "arcanist",
    domainDesc: "Arcanum_of_the_Wheel_domains",
    index: 8,
    dismiss: "",
    dismissDesc: "Arcanum_of_the_Wheel_dismiss",
    showInPlayerSheet: true,
    merge: "",
    mergeDesc: "Arcanum_of_the_Wheel_merge",
  },
];

export const entropistGamble = {
  fuid: "gamble",
  spellType: "gamble",
  spellName: t("Gamble"),
  cost: { resource: "mp", amount: 10, perTarget: true },
  maxTargets: 2,
  targetDescription: "Special",
  duration: "Instantaneous",
  attr: "will",
  targets: [
    {
      rangeFrom: 1,
      rangeTo: 1,
      effect: t("GambleEffect1"),
      secondRoll: false,
      secondEffects: [],
    },
    {
      rangeFrom: 2,
      rangeTo: 3,
      effect: t("GambleEffect2"),
      secondRoll: false,
      secondEffects: [],
    },
    {
      rangeFrom: 4,
      rangeTo: 6,
      effect: t("GambleEffect3"),
      secondRoll: false,
      secondEffects: [],
    },
    {
      rangeFrom: 7,
      rangeTo: 8,
      effect: t("GambleEffect4"),
      secondRoll: false,
      secondEffects: [],
    },
    {
      rangeFrom: 9,
      rangeTo: 12,
      effect: t("GambleEffect5"),
      secondRoll: true,
      secondEffects: [
        {
          dieValue: 1,
          effect: t("wind"),
        },
        {
          dieValue: 2,
          effect: t("bolt"),
        },
        {
          dieValue: 3,
          effect: t("dark"),
        },
        {
          dieValue: 4,
          effect: t("earth"),
        },
        {
          dieValue: 5,
          effect: t("fire"),
        },
        {
          dieValue: 6,
          effect: t("poison"),
        },
      ],
    },
  ],
};

const slugify = (value = "") =>
  String(value)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

classList.forEach((item) => {
  if (item.fuid === undefined && item.name) item.fuid = slugify(item.name);
});
spellList.forEach((item) => {
  if (item.fuid === undefined && item.name) item.fuid = slugify(item.name);
});
arcanumList.forEach((item) => {
  if (item.fuid === undefined && item.name) item.fuid = slugify(item.name);
});

export default classList;
