export const officialEffects = [
  // Accuracy
  {
    fuid: "all-accuracy-boost",
    itemType: "effect",
    name: "Accuracy Boost",
    description: "Increases all attack accuracy by 2.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.accuracy.all", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "melee-accuracy-boost",
    itemType: "effect",
    name: "Melee Accuracy Boost",
    description: "Increases melee attack accuracy by 2.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.accuracy.melee", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "ranged-accuracy-boost",
    itemType: "effect",
    name: "Ranged Accuracy Boost",
    description: "Increases ranged attack accuracy by 2.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.accuracy.ranged", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "magic-accuracy-boost",
    itemType: "effect",
    name: "Magic Accuracy Boost",
    description: "Increases magic attack accuracy by 2.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.accuracy.magic", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },

  // Damage
  {
    fuid: "all-damage-boost",
    itemType: "effect",
    name: "Damage Boost",
    description: "Increases all attack damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.damage.all", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "melee-damage-boost",
    itemType: "effect",
    name: "Melee Damage Boost",
    description: "Increases melee attack damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.damage.melee", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "ranged-damage-boost",
    itemType: "effect",
    name: "Ranged Damage Boost",
    description: "Increases ranged attack damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.damage.ranged", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "spell-damage-boost",
    itemType: "effect",
    name: "Spell Damage Boost",
    description: "Increases spell damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.damage.spell", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },

  // Incoming Damage Reduction
  {
    fuid: "damage-reduction",
    itemType: "effect",
    name: "Damage Reduction",
    description: "Reduces all incoming damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.all", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "fire-ward",
    itemType: "effect",
    name: "Fire Ward",
    description: "Reduces incoming fire damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.fire", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "ice-ward",
    itemType: "effect",
    name: "Ice Ward",
    description: "Reduces incoming ice damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.ice", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "bolt-ward",
    itemType: "effect",
    name: "Bolt Ward",
    description: "Reduces incoming lightning damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.lightning", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "earth-ward",
    itemType: "effect",
    name: "Earth Ward",
    description: "Reduces incoming earth damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.earth", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "air-ward",
    itemType: "effect",
    name: "Air Ward",
    description: "Reduces incoming air damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.air", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "dark-ward",
    itemType: "effect",
    name: "Dark Ward",
    description: "Reduces incoming dark damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.dark", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "light-ward",
    itemType: "effect",
    name: "Light Ward",
    description: "Reduces incoming light damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.light", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "poison-ward",
    itemType: "effect",
    name: "Poison Ward",
    description: "Reduces incoming poison damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.poison", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "physical-ward",
    itemType: "effect",
    name: "Physical Ward",
    description: "Reduces incoming physical damage by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingDamage.physical", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },

  // Affinities: Resistance
  {
    fuid: "physical-resistance",
    itemType: "effect",
    name: "Physical Resistance",
    description: "Grants resistance to physical damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.physical", mode: 4, value: "rs" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "fire-resistance",
    itemType: "effect",
    name: "Fire Resistance",
    description: "Grants resistance to fire damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.fire", mode: 4, value: "rs" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "ice-resistance",
    itemType: "effect",
    name: "Ice Resistance",
    description: "Grants resistance to ice damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.ice", mode: 4, value: "rs" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "bolt-resistance",
    itemType: "effect",
    name: "Bolt Resistance",
    description: "Grants resistance to lightning damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.bolt", mode: 4, value: "rs" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "earth-resistance",
    itemType: "effect",
    name: "Earth Resistance",
    description: "Grants resistance to earth damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.earth", mode: 4, value: "rs" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "air-resistance",
    itemType: "effect",
    name: "Air Resistance",
    description: "Grants resistance to air damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.air", mode: 4, value: "rs" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "dark-resistance",
    itemType: "effect",
    name: "Dark Resistance",
    description: "Grants resistance to dark damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.dark", mode: 4, value: "rs" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "light-resistance",
    itemType: "effect",
    name: "Light Resistance",
    description: "Grants resistance to light damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.light", mode: 4, value: "rs" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "poison-resistance",
    itemType: "effect",
    name: "Poison Resistance",
    description: "Grants resistance to poison damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.poison", mode: 4, value: "rs" }],
    meta: { book: "core", isOfficial: true },
  },

  // Affinities: Immunity
  {
    fuid: "fire-immunity",
    itemType: "effect",
    name: "Fire Immunity",
    description: "Grants immunity to fire damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.fire", mode: 4, value: "im" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "ice-immunity",
    itemType: "effect",
    name: "Ice Immunity",
    description: "Grants immunity to ice damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.ice", mode: 4, value: "im" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "bolt-immunity",
    itemType: "effect",
    name: "Bolt Immunity",
    description: "Grants immunity to lightning damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.bolt", mode: 4, value: "im" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "earth-immunity",
    itemType: "effect",
    name: "Earth Immunity",
    description: "Grants immunity to earth damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.earth", mode: 4, value: "im" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "air-immunity",
    itemType: "effect",
    name: "Air Immunity",
    description: "Grants immunity to air damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.air", mode: 4, value: "im" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "dark-immunity",
    itemType: "effect",
    name: "Dark Immunity",
    description: "Grants immunity to dark damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.dark", mode: 4, value: "im" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "light-immunity",
    itemType: "effect",
    name: "Light Immunity",
    description: "Grants immunity to light damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.light", mode: 4, value: "im" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "poison-immunity",
    itemType: "effect",
    name: "Poison Immunity",
    description: "Grants immunity to poison damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.poison", mode: 4, value: "im" }],
    meta: { book: "core", isOfficial: true },
  },

  // Affinities: Absorption
  {
    fuid: "fire-absorption",
    itemType: "effect",
    name: "Fire Absorption",
    description: "Grants absorption to fire damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.fire", mode: 4, value: "ab" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "ice-absorption",
    itemType: "effect",
    name: "Ice Absorption",
    description: "Grants absorption to ice damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.ice", mode: 4, value: "ab" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "bolt-absorption",
    itemType: "effect",
    name: "Bolt Absorption",
    description: "Grants absorption to lightning damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.bolt", mode: 4, value: "ab" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "dark-absorption",
    itemType: "effect",
    name: "Dark Absorption",
    description: "Grants absorption to dark damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.dark", mode: 4, value: "ab" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "light-absorption",
    itemType: "effect",
    name: "Light Absorption",
    description: "Grants absorption to light damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.light", mode: 4, value: "ab" }],
    meta: { book: "core", isOfficial: true },
  },

  // Affinities: Vulnerability
  {
    fuid: "fire-vulnerability",
    itemType: "effect",
    name: "Fire Vulnerability",
    description: "Grants vulnerability to fire damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.fire", mode: 0, value: "vu" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "ice-vulnerability",
    itemType: "effect",
    name: "Ice Vulnerability",
    description: "Grants vulnerability to ice damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.ice", mode: 0, value: "vu" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "bolt-vulnerability",
    itemType: "effect",
    name: "Bolt Vulnerability",
    description: "Grants vulnerability to lightning damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.bolt", mode: 0, value: "vu" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "poison-vulnerability",
    itemType: "effect",
    name: "Poison Vulnerability",
    description: "Grants vulnerability to poison damage.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "affinities.poison", mode: 0, value: "vu" }],
    meta: { book: "core", isOfficial: true },
  },

  // Recovery Bonuses
  {
    fuid: "hp-recovery-boost",
    itemType: "effect",
    name: "HP Recovery Boost",
    description: "Increases incoming HP recovery by 5.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingRecovery.hp", mode: 2, value: "5" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "mp-recovery-boost",
    itemType: "effect",
    name: "MP Recovery Boost",
    description: "Increases incoming MP recovery by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingRecovery.mp", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "ip-recovery-boost",
    itemType: "effect",
    name: "IP Recovery Boost",
    description: "Increases incoming IP recovery by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingRecovery.ip", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "hp-outgoing-recovery-boost",
    itemType: "effect",
    name: "Healing Boost",
    description: "Increases outgoing HP recovery (healing dealt) by 5.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.outgoingRecovery.hp", mode: 2, value: "5" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "healing-multiplier",
    itemType: "effect",
    name: "Healing Amplifier",
    description: "Multiplies outgoing HP recovery by 1.5x.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "multipliers.outgoingRecovery.hp", mode: 1, value: "1.5" }],
    meta: { book: "core", isOfficial: true },
  },

  // Loss Reduction
  {
    fuid: "hp-loss-reduction",
    itemType: "effect",
    name: "HP Loss Reduction",
    description: "Reduces incoming HP loss by 3.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingLoss.hp", mode: 2, value: "-3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "mp-loss-reduction",
    itemType: "effect",
    name: "MP Loss Reduction",
    description: "Reduces incoming MP loss by 2.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingLoss.mp", mode: 2, value: "-2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "ip-loss-reduction",
    itemType: "effect",
    name: "IP Loss Reduction",
    description: "Reduces incoming IP loss by 2.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "bonuses.incomingLoss.ip", mode: 2, value: "-2" }],
    meta: { book: "core", isOfficial: true },
  },

  // Multipliers
  {
    fuid: "hp-loss-multiplier-half",
    itemType: "effect",
    name: "Half HP Loss",
    description: "Halves all incoming HP loss.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "multipliers.incomingLoss.hp", mode: 1, value: "0.5" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "hp-loss-multiplier-double",
    itemType: "effect",
    name: "Double HP Loss",
    description: "Doubles all incoming HP loss.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "multipliers.incomingLoss.hp", mode: 1, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "hp-recovery-multiplier",
    itemType: "effect",
    name: "Recovery Amplifier",
    description: "Multiplies incoming HP recovery by 1.5x.",
    trigger: { kind: "passive" },
    transfer: true,
    changes: [{ key: "multipliers.incomingRecovery.hp", mode: 1, value: "1.5" }],
    meta: { book: "core", isOfficial: true },
  },

  // Weapon (item-scoped, transfer: false)
  {
    fuid: "weapon-accuracy-bonus",
    itemType: "effect",
    name: "Weapon Accuracy Bonus",
    description: "Adds +2 to the weapon's accuracy value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["weapon"],
    changes: [{ key: "accuracy.value", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "weapon-damage-bonus",
    itemType: "effect",
    name: "Weapon Damage Bonus",
    description: "Adds +3 to the weapon's damage value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["weapon"],
    changes: [{ key: "damage.value", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },

  // Custom Weapon (item-scoped, transfer: false)
  {
    fuid: "custom-weapon-accuracy-bonus",
    itemType: "effect",
    name: "Custom Weapon Accuracy Bonus",
    description: "Adds +2 to the custom weapon's accuracy value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["customWeapon"],
    changes: [{ key: "accuracy.value", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "custom-weapon-damage-bonus",
    itemType: "effect",
    name: "Custom Weapon Damage Bonus",
    description: "Adds +3 to the custom weapon's damage value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["customWeapon"],
    changes: [{ key: "damage.value", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },

  // Armor (item-scoped, transfer: false)
  {
    fuid: "armor-def-bonus",
    itemType: "effect",
    name: "Armor DEF Bonus",
    description: "Adds +1 to the armor's base DEF value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["armor"],
    changes: [{ key: "def", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "armor-mdef-bonus",
    itemType: "effect",
    name: "Armor MDEF Bonus",
    description: "Adds +1 to the armor's base MDEF value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["armor"],
    changes: [{ key: "mdef", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "armor-init-bonus",
    itemType: "effect",
    name: "Armor Initiative Bonus",
    description: "Adds +1 to the armor's initiative modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["armor"],
    changes: [{ key: "init", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "armor-modifier-def",
    itemType: "effect",
    name: "Armor DEF Modifier",
    description: "Adds +1 to the armor's DEF modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["armor"],
    changes: [{ key: "modifiers.def", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "armor-modifier-mdef",
    itemType: "effect",
    name: "Armor MDEF Modifier",
    description: "Adds +1 to the armor's MDEF modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["armor"],
    changes: [{ key: "modifiers.mdef", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "armor-modifier-init",
    itemType: "effect",
    name: "Armor Initiative Modifier",
    description: "Adds +1 to the armor's initiative modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["armor"],
    changes: [{ key: "modifiers.init", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "armor-modifier-accuracy",
    itemType: "effect",
    name: "Armor Accuracy Modifier",
    description: "Adds +2 to the armor's accuracy modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["armor"],
    changes: [{ key: "modifiers.accuracy", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "armor-modifier-damage-melee",
    itemType: "effect",
    name: "Armor Melee Damage Modifier",
    description: "Adds +3 to the armor's melee damage modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["armor"],
    changes: [{ key: "modifiers.damageMelee", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "armor-modifier-damage-ranged",
    itemType: "effect",
    name: "Armor Ranged Damage Modifier",
    description: "Adds +3 to the armor's ranged damage modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["armor"],
    changes: [{ key: "modifiers.damageRanged", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },

  // Shield (item-scoped, transfer: false)
  {
    fuid: "shield-def-bonus",
    itemType: "effect",
    name: "Shield DEF Bonus",
    description: "Adds +1 to the shield's base DEF value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["shield"],
    changes: [{ key: "def", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "shield-mdef-bonus",
    itemType: "effect",
    name: "Shield MDEF Bonus",
    description: "Adds +1 to the shield's base MDEF value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["shield"],
    changes: [{ key: "mdef", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "shield-init-bonus",
    itemType: "effect",
    name: "Shield Initiative Bonus",
    description: "Adds +1 to the shield's initiative modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["shield"],
    changes: [{ key: "init", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "shield-modifier-def",
    itemType: "effect",
    name: "Shield DEF Modifier",
    description: "Adds +1 to the shield's DEF modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["shield"],
    changes: [{ key: "modifiers.def", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "shield-modifier-mdef",
    itemType: "effect",
    name: "Shield MDEF Modifier",
    description: "Adds +1 to the shield's MDEF modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["shield"],
    changes: [{ key: "modifiers.mdef", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "shield-modifier-init",
    itemType: "effect",
    name: "Shield Initiative Modifier",
    description: "Adds +1 to the shield's initiative modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["shield"],
    changes: [{ key: "modifiers.init", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "shield-modifier-accuracy",
    itemType: "effect",
    name: "Shield Accuracy Modifier",
    description: "Adds +2 to the shield's accuracy modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["shield"],
    changes: [{ key: "modifiers.accuracy", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "shield-modifier-damage-melee",
    itemType: "effect",
    name: "Shield Melee Damage Modifier",
    description: "Adds +3 to the shield's melee damage modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["shield"],
    changes: [{ key: "modifiers.damageMelee", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "shield-modifier-damage-ranged",
    itemType: "effect",
    name: "Shield Ranged Damage Modifier",
    description: "Adds +3 to the shield's ranged damage modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["shield"],
    changes: [{ key: "modifiers.damageRanged", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },

  // Accessory (item-scoped, transfer: false)
  {
    fuid: "accessory-modifier-def",
    itemType: "effect",
    name: "Accessory DEF Modifier",
    description: "Adds +1 to the accessory's DEF modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["accessory"],
    changes: [{ key: "modifiers.def", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "accessory-modifier-mdef",
    itemType: "effect",
    name: "Accessory MDEF Modifier",
    description: "Adds +1 to the accessory's MDEF modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["accessory"],
    changes: [{ key: "modifiers.mdef", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "accessory-modifier-init",
    itemType: "effect",
    name: "Accessory Initiative Modifier",
    description: "Adds +1 to the accessory's initiative modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["accessory"],
    changes: [{ key: "modifiers.init", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "accessory-modifier-accuracy",
    itemType: "effect",
    name: "Accessory Accuracy Modifier",
    description: "Adds +2 to the accessory's accuracy modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["accessory"],
    changes: [{ key: "modifiers.accuracy", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "accessory-modifier-damage-melee",
    itemType: "effect",
    name: "Accessory Melee Damage Modifier",
    description: "Adds +3 to the accessory's melee damage modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["accessory"],
    changes: [{ key: "modifiers.damageMelee", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "accessory-modifier-damage-ranged",
    itemType: "effect",
    name: "Accessory Ranged Damage Modifier",
    description: "Adds +3 to the accessory's ranged damage modifier.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["accessory"],
    changes: [{ key: "modifiers.damageRanged", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },

  // NPC Attack (item-scoped, transfer: false)
  {
    fuid: "npc-attack-accuracy-bonus",
    itemType: "effect",
    name: "NPC Attack Accuracy Bonus",
    description: "Adds +2 to the NPC attack's accuracy value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcAttack"],
    changes: [{ key: "accuracy.value", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-attack-damage-bonus",
    itemType: "effect",
    name: "NPC Attack Damage Bonus",
    description: "Adds +3 to the NPC attack's damage value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcAttack"],
    changes: [{ key: "damage.value", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-attack-attr1-override",
    itemType: "effect",
    name: "NPC Attack Attr1 Override",
    description: "Overrides the NPC attack's first accuracy attribute to Dexterity.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcAttack"],
    changes: [{ key: "attr1", mode: 0, value: "dexterity" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-attack-attr2-override",
    itemType: "effect",
    name: "NPC Attack Attr2 Override",
    description: "Overrides the NPC attack's second accuracy attribute to Might.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcAttack"],
    changes: [{ key: "attr2", mode: 0, value: "might" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-attack-defense-override",
    itemType: "effect",
    name: "NPC Attack Defense Override",
    description: "Overrides the NPC attack's targeted defense to Magic Defense.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcAttack"],
    changes: [{ key: "defense", mode: 0, value: "mdef" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-attack-damage-type-override",
    itemType: "effect",
    name: "NPC Attack Damage Type Override",
    description: "Overrides the NPC attack's damage type to Fire.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcAttack"],
    changes: [{ key: "damage.type", mode: 0, value: "fire" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-attack-range-override",
    itemType: "effect",
    name: "NPC Attack Range Override",
    description: "Overrides the NPC attack's range to Ranged.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcAttack"],
    changes: [{ key: "range", mode: 0, value: "ranged" }],
    meta: { book: "core", isOfficial: true },
  },

  // NPC Spell (item-scoped, transfer: false)
  {
    fuid: "npc-spell-accuracy-bonus",
    itemType: "effect",
    name: "NPC Spell Accuracy Bonus",
    description: "Adds +2 to the NPC spell's accuracy value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "accuracy.value", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-spell-damage-bonus",
    itemType: "effect",
    name: "NPC Spell Damage Bonus",
    description: "Adds +3 to the NPC spell's damage value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "damage.value", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-spell-attr1-override",
    itemType: "effect",
    name: "NPC Spell Attr1 Override",
    description: "Overrides the NPC spell's first accuracy attribute to Will.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "attr1", mode: 0, value: "will" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-spell-attr2-override",
    itemType: "effect",
    name: "NPC Spell Attr2 Override",
    description: "Overrides the NPC spell's second accuracy attribute to Insight.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "attr2", mode: 0, value: "insight" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-spell-defense-override",
    itemType: "effect",
    name: "NPC Spell Defense Override",
    description: "Overrides the NPC spell's targeted defense to Magic Defense.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "defense", mode: 0, value: "mdef" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-spell-damage-type-override",
    itemType: "effect",
    name: "NPC Spell Damage Type Override",
    description: "Overrides the NPC spell's damage type to Dark.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "damage.type", mode: 0, value: "dark" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-spell-hr-zero",
    itemType: "effect",
    name: "NPC Spell HR Zero",
    description: "Sets the NPC spell to ignore the high roll on damage.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "damage.hrZero", mode: 0, value: "true" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-spell-range-override",
    itemType: "effect",
    name: "NPC Spell Range Override",
    description: "Overrides the NPC spell's range to Ranged.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "range", mode: 0, value: "ranged" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-spell-cost-reduction",
    itemType: "effect",
    name: "NPC Spell Cost Reduction",
    description: "Reduces the NPC spell's MP cost by 10.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "cost.amount", mode: 2, value: "-10" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "npc-spell-max-targets-bonus",
    itemType: "effect",
    name: "NPC Spell Max Targets Bonus",
    description: "Adds +1 to the NPC spell's maximum targets.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["npcSpell"],
    changes: [{ key: "maxTargets", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },

  // Player Spell (item-scoped, transfer: false)
  {
    fuid: "player-spell-accuracy-bonus",
    itemType: "effect",
    name: "Player Spell Accuracy Bonus",
    description: "Adds +2 to the player spell's accuracy value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["playerSpell"],
    changes: [{ key: "accuracy.value", mode: 2, value: "2" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "player-spell-damage-bonus",
    itemType: "effect",
    name: "Player Spell Damage Bonus",
    description: "Adds +3 to the player spell's damage value.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["playerSpell"],
    changes: [{ key: "damage.value", mode: 2, value: "3" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "player-spell-cost-reduction",
    itemType: "effect",
    name: "Player Spell Cost Reduction",
    description: "Reduces the player spell's MP cost by 10.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["playerSpell"],
    changes: [{ key: "cost.amount", mode: 2, value: "-10" }],
    meta: { book: "core", isOfficial: true },
  },
  {
    fuid: "player-spell-max-targets-bonus",
    itemType: "effect",
    name: "Player Spell Max Targets Bonus",
    description: "Adds +1 to the player spell's maximum targets.",
    trigger: { kind: "passive" },
    transfer: false,
    applicableTypes: ["playerSpell"],
    changes: [{ key: "maxTargets", mode: 2, value: "1" }],
    meta: { book: "core", isOfficial: true },
  },
];
