export const baseWeapons = [
  {
    category: "Arcane",
    name: "Staff",
    cost: 100,
    att1: "will",
    att2: "will",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    range: "melee",
  },
  {
    category: "Arcane",
    name: "Tome",
    cost: 100,
    att1: "insight",
    att2: "insight",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    range: "melee",
  },
  {
    category: "Bow",
    name: "Crossbow",
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    range: "distance",
  },
  {
    category: "Bow",
    name: "Shortbow",
    cost: 200,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    range: "distance",
  },
  {
    category: "Flail",
    name: "Chain Whip",
    cost: 150,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    range: "melee",
  },
  {
    category: "Firearm",
    name: "Pistol",
    cost: 250,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    range: "distance",
  },
  {
    category: "Spear",
    name: "Light Spear",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    range: "melee",
  },
  {
    category: "Spear",
    name: "Heavy Spear",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 12,
    type: "physical",
    hands: 2,
    range: "melee",
  },
  {
    category: "Thrown",
    name: "Shuriken",
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 4,
    type: "physical",
    hands: 1,
    range: "distance",
  },
  {
    category: "Heavy",
    name: "Iron Hammer",
    cost: 200,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    range: "melee",
  },
  {
    category: "Heavy",
    name: "Broadaxe",
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 10,
    type: "physical",
    hands: 1,
    range: "melee",
  },
  {
    category: "Heavy",
    name: "Waraxe",
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 14,
    type: "physical",
    hands: 2,
    range: "melee",
  },
  {
    category: "Dagger",
    name: "Steel Dagger",
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 4,
    type: "physical",
    hands: 1,
    range: "melee",
  },
  {
    category: "Brawling",
    name: "Iron Knuckle",
    cost: 150,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    range: "melee",
  },
  {
    category: "Sword",
    name: "Katana",
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    range: "melee",
  },
  {
    category: "Sword",
    name: "Bronze Sword",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    range: "melee",
  },
  {
    category: "Sword",
    name: "Greatsword",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    range: "melee",
  },
  {
    category: "Sword",
    name: "Rapier",
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    range: "melee",
  },
];

export const baseArmors = [
  {
    name: "No Armor",
    cost: 0,
    def: 0,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: 0,
  },
  {
    name: "Travel Garb",
    cost: 100,
    def: 0,
    defbonus: 1,
    mdef: 0,
    mdefbonus: 1,
    init: -1,
  },
  {
    name: "Silk Shirt",
    cost: 100,
    def: 0,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 2,
    init: -1,
  },
  {
    name: "Combat Tunic",
    cost: 150,
    def: 0,
    defbonus: 1,
    mdef: 0,
    mdefbonus: 1,
    init: 0,
  },
  {
    name: "Sage Robe",
    cost: 200,
    def: 0,
    defbonus: 1,
    mdef: 0,
    mdefbonus: 2,
    init: -2,
  },
  {
    name: "Brigandine",
    cost: 150,
    def: 10,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: -2,
  },
  {
    name: "Bronze Plate",
    cost: 200,
    def: 11,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: -3,
  },
  {
    name: "Runic Plate",
    cost: 250,
    def: 11,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 1,
    init: -3,
  },
  {
    name: "Steel Plate",
    cost: 300,
    def: 12,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: -4,
  },
];

export const baseShields = [
  {
    name: "No Shield",
    cost: 0,
    def: 0,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: 0,
  },
  {
    name: "Bronze Shield",
    cost: 100,
    def: 0,
    defbonus: 2,
    mdef: 0,
    mdefbonus: 0,
    init: 0,
  },
  {
    name: "Runic Shield",
    cost: 150,
    def: 0,
    defbonus: 2,
    mdef: 0,
    mdefbonus: 2,
    init: 0,
  },
];
