import { t } from "../translation/translate";

export const baseWeapons = [
  {
    category: "Arcane",
    name: t("Staff", true),
    cost: 100,
    att1: "will",
    att2: "will",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    range: "melee",
    martial: false
  },
  {
    category: "Arcane",
    name: t("Tome", true),
    cost: 100,
    att1: "insight",
    att2: "insight",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    range: "melee",
    martial: false
  },
  {
    category: "Bow",
    name: t("Crossbow", true),
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    range: "distance",
    martial: false
  },
  {
    category: "Bow",
    name: t("Shortbow", true),
    cost: 200,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    range: "distance",
    martial: false
  },
  {
    category: "Flail",
    name: t("Chain Whip", true),
    cost: 150,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    range: "melee",
    martial: false
  },
  {
    category: "Firearm",
    name: t("Pistol", true),
    cost: 250,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    range: "distance",
    martial: true
  },
  {
    category: "Spear",
    name: t("Light Spear", true),
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    range: "melee",
    martial: true
  },
  {
    category: "Spear",
    name: t("Heavy Spear", true),
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 12,
    type: "physical",
    hands: 2,
    range: "melee",
    martial: true
  },
  {
    category: "Thrown",
    name: t("Shuriken", true),
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 4,
    type: "physical",
    hands: 1,
    range: "distance",
    martial: false
  },
  {
    category: "Heavy",
    name: t("Iron Hammer", true),
    cost: 200,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    range: "melee",
    martial: false
  },
  {
    category: "Heavy",
    name: t("Broadaxe", true),
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 10,
    type: "physical",
    hands: 1,
    range: "melee",
    martial: true
  },
  {
    category: "Heavy",
    name: t("Waraxe", true),
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 14,
    type: "physical",
    hands: 2,
    range: "melee",
    martial: true
  },
  {
    category: "Dagger",
    name: t("Steel Dagger", true),
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 4,
    type: "physical",
    hands: 1,
    range: "melee",
    martial: false
  },
  {
    category: "Brawling",
    name: t("Iron Knuckle", true),
    cost: 150,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    range: "melee",
    martial: false
  },
  {
    category: "Sword",
    name: t("Katana", true),
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    range: "melee",
    martial: true
  },
  {
    category: "Sword",
    name: t("Bronze Sword", true),
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    range: "melee",
    martial: true
  },
  {
    category: "Sword",
    name: t("Greatsword", true),
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    range: "melee",
    martial: true
  },
  {
    category: "Sword",
    name: t("Rapier", true),
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    range: "melee",
    martial: true
  },
];

export const baseArmors = [
  {
    name: t("No Armor", true),
    cost: 0,
    def: 0,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: 0,
    martial: false
  },
  {
    name: t("Travel Garb", true),
    cost: 100,
    def: 0,
    defbonus: 1,
    mdef: 0,
    mdefbonus: 1,
    init: -1,
    martial: false
  },
  {
    name: t("Silk Shirt", true),
    cost: 100,
    def: 0,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 2,
    init: -1,
    martial: false
  },
  {
    name: t("Combat Tunic", true),
    cost: 150,
    def: 0,
    defbonus: 1,
    mdef: 0,
    mdefbonus: 1,
    init: 0,
    martial: false
  },
  {
    name: t("Sage Robe", true),
    cost: 200,
    def: 0,
    defbonus: 1,
    mdef: 0,
    mdefbonus: 2,
    init: -2,
    martial: false
  },
  {
    name: t("Brigandine", true),
    cost: 150,
    def: 10,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: -2,
    martial: true
  },
  {
    name: t("Bronze Plate", true),
    cost: 200,
    def: 11,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: -3,
    martial: true
  },
  {
    name: t("Runic Plate", true),
    cost: 250,
    def: 11,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 1,
    init: -3,
    martial: true
  },
  {
    name: t("Steel Plate", true),
    cost: 300,
    def: 12,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: -4,
    martial: true
  },
];

export const baseShields = [
  {
    name: t("No Shield", true),
    cost: 0,
    def: 0,
    defbonus: 0,
    mdef: 0,
    mdefbonus: 0,
    init: 0,
    martial: false
  },
  {
    name: t("Bronze Shield", true),
    cost: 100,
    def: 0,
    defbonus: 2,
    mdef: 0,
    mdefbonus: 0,
    init: 0,
    martial: false
  },
  {
    name: t("Runic Shield", true),
    cost: 150,
    def: 0,
    defbonus: 2,
    mdef: 0,
    mdefbonus: 2,
    init: 0,
    martial: true
  },
];
