import { slugify } from "./slugify";

const magiseeds = [
  {
    fuid: "arctic-narcissus",
    name: "magiseed_arctic_narcissus",
    description: "magiseed_arctic_narcissus_desc",
    rangeStart: 0,
    rangeEnd: 3,
    effects: {
      0: "magiseed_arctic_narcissus_effect_0",
      1: "magiseed_arctic_narcissus_effect_1",
      2: "magiseed_arctic_narcissus_effect_2",
      3: "magiseed_arctic_narcissus_effect_3",
    },
  },
  {
    fuid: "blazing-chrysanthemum",
    name: "magiseed_blazing_chrysanthemum",
    description: "magiseed_blazing_chrysanthemum_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_blazing_chrysanthemum_effect_1",
      2: "magiseed_blazing_chrysanthemum_effect_2",
      3: "magiseed_blazing_chrysanthemum_effect_3",
    },
  },
  {
    fuid: "desert-dahlia",
    name: "magiseed_desert_dahlia",
    description: "magiseed_desert_dahlia_desc",
    rangeStart: 0,
    rangeEnd: 3,
    effects: {
      0: "magiseed_desert_dahlia_effect_0",
      1: "magiseed_desert_dahlia_effect_1",
      2: "magiseed_desert_dahlia_effect_2",
      3: "magiseed_desert_dahlia_effect_3",
    },
  },
  {
    fuid: "golden-ginkgo",
    name: "magiseed_golden_ginkgo",
    description: "magiseed_golden_ginkgo_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_golden_ginkgo_effect_1",
      2: "magiseed_golden_ginkgo_effect_2",
      3: "magiseed_golden_ginkgo_effect_3",
    },
  },
  {
    fuid: "grave-asphodel",
    name: "magiseed_grave_asphodel",
    description: "magiseed_grave_asphodel_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_grave_asphodel_effect_1",
      2: "magiseed_grave_asphodel_effect_2",
      3: "magiseed_grave_asphodel_effect_3",
    },
  },
  {
    fuid: "hermit-iris",
    name: "magiseed_hermit_iris",
    description: "magiseed_hermit_iris_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_hermit_iris_effect_1",
      2: "magiseed_hermit_iris_effect_2",
      3: "magiseed_hermit_iris_effect_3",
    },
  },
  {
    fuid: "hookleaf-nightshade",
    name: "magiseed_hookleaf_nightshade",
    description: "magiseed_hookleaf_nightshade_desc",
    rangeStart: 0,
    rangeEnd: 3,
    effects: {
      0: "magiseed_hookleaf_nightshade_effect_0",
      1: "magiseed_hookleaf_nightshade_effect_1",
      2: "magiseed_hookleaf_nightshade_effect_2",
      3: "magiseed_hookleaf_nightshade_effect_3",
    },
  },
  {
    fuid: "horned-hawthorn",
    name: "magiseed_horned_hawthorn",
    description: "magiseed_horned_hawthorn_desc",
    rangeStart: 0,
    rangeEnd: 3,
    effects: {
      0: "magiseed_horned_hawthorn_effect_0",
      1: "magiseed_horned_hawthorn_effect_1",
      2: "magiseed_horned_hawthorn_effect_2",
      3: "magiseed_horned_hawthorn_effect_3",
    },
  },
  {
    fuid: "lunar-magnolia",
    name: "magiseed_lunar_magnolia",
    description: "magiseed_lunar_magnolia_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_lunar_magnolia_effect_1",
      2: "magiseed_lunar_magnolia_effect_2",
      3: "magiseed_lunar_magnolia_effect_3",
    },
  },
  {
    fuid: "ocean-lotus",
    name: "magiseed_ocean_lotus",
    description: "magiseed_ocean_lotus_desc",
    rangeStart: 0,
    rangeEnd: 3,
    effects: {
      0: "magiseed_ocean_lotus_effect_0",
      1: "magiseed_ocean_lotus_effect_1",
      2: "magiseed_ocean_lotus_effect_2",
      3: "magiseed_ocean_lotus_effect_3",
    },
  },
  {
    fuid: "pilgrim-gazalia",
    name: "magiseed_pilgrim_gazalia",
    description: "magiseed_pilgrim_gazalia_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_pilgrim_gazalia_effect_1",
      2: "magiseed_pilgrim_gazalia_effect_2",
      3: "magiseed_pilgrim_gazalia_effect_3",
    },
  },
  {
    fuid: "prancing-dandelion",
    name: "magiseed_prancing_dandelion",
    description: "magiseed_prancing_dandelion_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_prancing_dandelion_effect_1",
      2: "magiseed_prancing_dandelion_effect_2",
      3: "magiseed_prancing_dandelion_effect_3",
    },
  },
  {
    fuid: "regal-protea",
    name: "magiseed_regal_protea",
    description: "magiseed_regal_protea_desc",
    rangeStart: 0,
    rangeEnd: 3,
    effects: {
      0: "magiseed_regal_protea_effect_0",
      1: "magiseed_regal_protea_effect_1",
      2: "magiseed_regal_protea_effect_2",
      3: "magiseed_regal_protea_effect_3",
    },
  },
  {
    fuid: "remedy-lily",
    name: "magiseed_remedy_lily",
    description: "magiseed_remedy_lily_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_remedy_lily_effect_1",
      2: "magiseed_remedy_lily_effect_2",
      3: "magiseed_remedy_lily_effect_3",
    },
  },
  {
    fuid: "serrated-rose",
    name: "magiseed_serrated_rose",
    description: "magiseed_serrated_rose_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_serrated_rose_effect_1",
      2: "magiseed_serrated_rose_effect_2",
      3: "magiseed_serrated_rose_effect_3",
    },
  },
  {
    fuid: "silver-strelitzia",
    name: "magiseed_silver_strelitzia",
    description: "magiseed_silver_strelitzia_desc",
    rangeStart: 0,
    rangeEnd: 3,
    effects: {
      0: "magiseed_silver_strelitzia_effect_0",
      1: "magiseed_silver_strelitzia_effect_1",
      2: "magiseed_silver_strelitzia_effect_2",
      3: "magiseed_silver_strelitzia_effect_3",
    },
  },
  {
    fuid: "star-peony",
    name: "magiseed_star_peony",
    description: "magiseed_star_peony_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_star_peony_effect_1",
      2: "magiseed_star_peony_effect_2",
      3: "magiseed_star_peony_effect_3",
    },
  },
  {
    fuid: "striped-orcoid",
    name: "magiseed_striped_orchid",
    description: "magiseed_striped_orchid_desc",
    rangeStart: 1,
    rangeEnd: 3,
    effects: {
      1: "magiseed_striped_orchid_effect_1",
      2: "magiseed_striped_orchid_effect_2",
      3: "magiseed_striped_orchid_effect_3",
    },
  },
  {
    fuid: "wardwattle",
    name: "magiseed_wardwattle",
    description: "magiseed_wardwattle_desc",
    rangeStart: 0,
    rangeEnd: 3,
    effects: {
      0: "magiseed_wardwattle_effect_0",
      1: "magiseed_wardwattle_effect_1",
      2: "magiseed_wardwattle_effect_2",
      3: "magiseed_wardwattle_effect_3",
    },
  },
  {
    fuid: "wrathful-carnation",
    name: "magiseed_wrathful_carnation",
    description: "magiseed_wrathful_carnation_desc",
    rangeStart: 1,
    rangeEnd: 4,
    effects: {
      1: "magiseed_wrathful_carnation_effect_1",
      2: "magiseed_wrathful_carnation_effect_2",
      3: "magiseed_wrathful_carnation_effect_3",
      4: "magiseed_wrathful_carnation_effect_4",
    },
  },
  {
    fuid: "custom-magiseed",
    name: "magiseed_custom",
    description: "",
    rangeStart: 0,
    rangeEnd: 3,
    effects: {
      0: "",
      1: "",
      2: "",
      3: "",
    },
  },
];

magiseeds.forEach((item) => {
  if (item.fuid === undefined && item.name) item.fuid = slugify(item.name);
});

export { magiseeds };
