import { t } from "../translation/translate";

const heroics = [
  // FUCR - core
  {
    name: t("adversity", true),
    quote: t("adversity_quote", true),
    description: t("adversity_desc", true),
    source: t("adversity_source", true),
    applicableTo: ["Darkblade"],
    book: "core",
  },
  {
    name: t("ambidextrous", true),
    quote: t("ambidextrous_quote", true),
    description: t("ambidextrous_desc", true),
    source: t("ambidextrous_source", true),
    applicableTo: [],
    book: "core",
  },
  {
    name: t("arcane_echoes", true),
    quote: t("arcane_echoes_quote", true),
    description: t("arcane_echoes_desc", true),
    source: t("arcane_echoes_source", true),
    applicableTo: ["Arcanist"],
    book: "core",
  },
  {
    name: t("chimeric_mastery", true),
    quote: t("chimeric_mastery_quote", true),
    description: t("chimeric_mastery_desc", true),
    source: t("chimeric_mastery_source", true),
    applicableTo: ["Chimerist"],
    book: "core",
  },
  {
    name: t("comet", true),
    quote: t("comet_quote", true),
    description: t("comet_desc", true),
    source: t("comet_source", true),
    applicableTo: ["Entropist"],
    book: "core",
  },
  {
    name: t("deep_pockets", true),
    quote: t("deep_pockets_quote", true),
    description: t("deep_pockets_desc", true),
    source: t("deep_pockets_source", true),
    applicableTo: ["Tinkerer"],
    book: "core",
  },
  {
    name: t("disarming_rhetoric", true),
    quote: t("disarming_rhetoric_quote", true),
    description: t("disarming_rhetoric_desc", true),
    source: t("disarming_rhetoric_source", true),
    applicableTo: ["Orator"],
    book: "core",
  },
  {
    name: t("extra_hp", true),
    quote: t("extra_hp_quote", true),
    description: t("extra_hp_desc", true),
    source: t("extra_hp_source", true),
    applicableTo: [],
    book: "core",
  },
  {
    name: t("extra_ip", true),
    quote: t("extra_ip_quote", true),
    description: t("extra_ip_desc", true),
    source: t("extra_ip_source", true),
    applicableTo: [],
    book: "core",
  },
  {
    name: t("extra_mp", true),
    quote: t("extra_mp_quote", true),
    description: t("extra_mp_desc", true),
    source: t("extra_mp_source", true),
    applicableTo: [],
    book: "core",
  },
  {
    name: t("extra_spells", true),
    quote: t("extra_spells_quote", true),
    description: t("extra_spells_desc", true),
    source: t("extra_spells_source", true),
    applicableTo: [],
    book: "core",
  },
  {
    name: t("heartbreaker", true),
    quote: t("heartbreaker_quote", true),
    description: t("heartbreaker_desc", true),
    source: t("heartbreaker_source", true),
    applicableTo: ["Darkblade"],
    book: "core",
  },
  {
    name: t("heroic_companion", true),
    quote: t("heroic_companion_quote", true),
    description: t("heroic_companion_desc", true),
    source: t("heroic_companion_source", true),
    applicableTo: ["Wayfarer"],
    book: "core",
  },
  {
    name: t("hope", true),
    quote: t("hope_quote", true),
    description: t("hope_desc", true),
    source: t("hope_source", true),
    applicableTo: ["Spiritist"],
    book: "core",
  },
  {
    name: t("mathemagic", true),
    quote: t("mathemagic_quote", true),
    description: t("mathemagic_desc", true),
    source: t("mathemagic_source", true),
    applicableTo: ["Loremaster"],
    book: "core",
  },
  {
    name: t("monkey_grip", true),
    quote: t("monkey_grip_quote", true),
    description: t("monkey_grip_desc", true),
    source: t("monkey_grip_source", true),
    applicableTo: ["Fury"],
    book: "core",
  },
  {
    name: t("perfect_aim", true),
    quote: t("perfect_aim_quote", true),
    description: t("perfect_aim_desc", true),
    source: t("perfect_aim_source", true),
    applicableTo: ["Sharpshooter"],
    book: "core",
  },
  {
    name: t("pillage", true),
    quote: t("pillage_quote", true),
    description: t("pillage_desc", true),
    source: t("pillage_source", true),
    applicableTo: ["Rogue"],
    book: "core",
  },
  {
    name: t("powerful_shot", true),
    quote: t("powerful_shot_quote", true),
    description: t("powerful_shot_desc", true),
    source: t("powerful_shot_source", true),
    applicableTo: ["Sharpshooter"],
    book: "core",
  },
  {
    name: t("powerful_spell", true),
    quote: t("powerful_spell_quote", true),
    description: t("powerful_spell_desc", true),
    source: t("powerful_spell_source", true),
    applicableTo: ["Chimerist", "Elementalist", "Entropist", "Spiritist"],
    book: "core",
  },
  {
    name: t("powerful_strike", true),
    quote: t("powerful_strike_quote", true),
    description: t("powerful_strike_desc", true),
    source: t("powerful_strike_source", true),
    applicableTo: ["Fury", "Weaponmaster"],
    book: "core",
  },
  {
    name: t("predictable", true),
    quote: t("predictable_quote", true),
    description: t("predictable_desc", true),
    source: t("predictable_source", true),
    applicableTo: ["Loremaster"],
    book: "core",
  },
  {
    name: t("rampart", true),
    quote: t("rampart_quote", true),
    description: t("rampart_desc", true),
    source: t("rampart_source", true),
    applicableTo: ["Guardian"],
    book: "core",
  },
  {
    name: t("repetition", true),
    quote: t("repetition_quote", true),
    description: t("repetition_desc", true),
    source: t("repetition_source", true),
    applicableTo: ["Orator"],
    book: "core",
  },
  {
    name: t("revelation", true),
    quote: t("revelation_quote", true),
    description: t("revelation_desc", true),
    source: t("revelation_source", true),
    applicableTo: ["Arcanist"],
    book: "core",
  },
  {
    name: t("status_immunity", true),
    quote: t("status_immunity_quote", true),
    description: t("status_immunity_desc", true),
    source: t("status_immunity_source", true),
    applicableTo: ["Wayfarer"],
    book: "core",
  },
  {
    name: t("tempest_strike", true),
    quote: t("tempest_strike_quote", true),
    description: t("tempest_strike_desc", true),
    source: t("tempest_strike_source", true),
    applicableTo: ["Weaponmaster"],
    book: "core",
  },
  {
    name: t("unbreakable", true),
    quote: t("unbreakable_quote", true),
    description: t("unbreakable_desc", true),
    source: t("unbreakable_source", true),
    applicableTo: ["Guardian"],
    book: "core",
  },
  {
    name: t("upgrade", true),
    quote: t("upgrade_quote", true),
    description: t("upgrade_desc", true),
    source: t("upgrade_source", true),
    applicableTo: ["Tinkerer"],
    book: "core",
  },
  {
    name: t("vanish", true),
    quote: t("vanish_quote", true),
    description: t("vanish_desc", true),
    source: t("vanish_source", true),
    applicableTo: ["Rogue"],
    book: "core",
  },
  {
    name: t("volcano", true),
    quote: t("volcano_quote", true),
    description: t("volcano_desc", true),
    source: t("volcano_source", true),
    applicableTo: ["Elementalist"],
    book: "core",
  },

  // FUHF - high
  {
    name: t("arcane_mark", true),
    quote: t("arcane_mark_quote", true),
    description: t("arcane_mark_desc", true),
    source: t("arcane_mark_source", true),
    applicableTo: ["Sharpshooter", "Symbolist", "Weaponmaster"],
    book: "high",
  },
  {
    name: t("bimagus", true),
    quote: t("bimagus_quote", true),
    description: t("bimagus_desc", true),
    source: t("bimagus_source", true),
    applicableTo: ["Elementalist", "Entropist", "Spiritist"],
    book: "high",
  },
  {
    name: t("blade_adept", true),
    quote: t("blade_adept_quote", true),
    description: t("blade_adept_desc", true),
    source: t("blade_adept_source", true),
    applicableTo: ["Rogue", "Weaponmaster"],
    book: "high",
  },
  {
    name: t("bullet_break", true),
    quote: t("bullet_break_quote", true),
    description: t("bullet_break_desc", true),
    source: t("bullet_break_source", true),
    applicableTo: ["Sharpshooter"],
    book: "high",
  },
  {
    name: t("ceaseless_battlefield", true),
    quote: t("ceaseless_battlefield_quote", true),
    description: t("ceaseless_battlefield_desc", true),
    source: t("ceaseless_battlefield_source", true),
    applicableTo: ["Commander"],
    book: "high",
  },
  {
    name: t("clean_slate", true),
    quote: t("clean_slate_quote", true),
    description: t("clean_slate_desc", true),
    source: t("clean_slate_source", true),
    applicableTo: ["Symbolist"],
    book: "high",
  },
  {
    name: t("double_arrow", true),
    quote: t("double_arrow_quote", true),
    description: t("double_arrow_desc", true),
    source: t("double_arrow_source", true),
    applicableTo: ["Commander", "Sharpshooter"],
    book: "high",
  },
  {
    name: t("fast_rituals", true),
    quote: t("fast_rituals_quote", true),
    description: t("fast_rituals_desc", true),
    source: t("fast_rituals_source", true),
    applicableTo: ["Chimerist", "Elementalist", "Entropist", "Spiritist"],
    book: "high",
  },
  {
    name: t("fleeting_moment", true),
    quote: t("fleeting_moment_quote", true),
    description: t("fleeting_moment_desc", true),
    source: t("fleeting_moment_source", true),
    applicableTo: ["Weaponmaster"],
    book: "high",
  },
  {
    name: t("grand_summoning", true),
    quote: t("grand_summoning_quote", true),
    description: t("grand_summoning_desc", true),
    source: t("grand_summoning_source", true),
    applicableTo: ["Arcanist"],
    book: "high",
  },
  {
    name: t("hoplite", true),
    quote: t("hoplite_quote", true),
    description: t("hoplite_desc", true),
    source: t("hoplite_source", true),
    applicableTo: ["Commander", "Guardian"],
    book: "high",
  },
  {
    name: t("iron_forest", true),
    quote: t("iron_forest_quote", true),
    description: t("iron_forest_desc", true),
    source: t("iron_forest_source", true),
    applicableTo: ["Commander", "Weaponmaster"],
    book: "high",
  },
  {
    name: t("magic_guard", true),
    quote: t("magic_guard_quote", true),
    description: t("magic_guard_desc", true),
    source: t("magic_guard_source", true),
    applicableTo: ["Chimerist", "Elementalist", "Entropist", "Spiritist"],
    book: "high",
  },
  {
    name: t("paso_doble", true),
    quote: t("paso_doble_quote", true),
    description: t("paso_doble_desc", true),
    source: t("paso_doble_source", true),
    applicableTo: ["Dancer"],
    book: "high",
  },
  {
    name: t("power_chord", true),
    quote: t("power_chord_quote", true),
    description: t("power_chord_desc", true),
    source: t("power_chord_source", true),
    applicableTo: ["Chanter"],
    book: "high",
  },
  {
    name: t("pulverizing_strike", true),
    quote: t("pulverizing_strike_quote", true),
    description: t("pulverizing_strike_desc", true),
    source: t("pulverizing_strike_source", true),
    applicableTo: ["Darkblade", "Fury", "Weaponmaster"],
    book: "high",
  },
  {
    name: t("rising_tide", true),
    quote: t("rising_tide_quote", true),
    description: t("rising_tide_desc", true),
    source: t("rising_tide_source", true),
    applicableTo: ["Fury", "Weaponmaster"],
    book: "high",
  },
  {
    name: t("ritual_seals", true),
    quote: t("ritual_seals_quote", true),
    description: t("ritual_seals_desc", true),
    source: t("ritual_seals_source", true),
    applicableTo: ["Symbolist"],
    book: "high",
  },
  {
    name: t("showstopper", true),
    quote: t("showstopper_quote", true),
    description: t("showstopper_desc", true),
    source: t("showstopper_source", true),
    applicableTo: ["Dancer"],
    book: "high",
  },
  {
    name: t("spider_s_web", true),
    quote: t("spider_s_web_quote", true),
    description: t("spider_s_web_desc", true),
    source: t("spider_s_web_source", true),
    applicableTo: ["Fury", "Weaponmaster"],
    book: "high",
  },
  {
    name: t("swirling_swarm", true),
    quote: t("swirling_swarm_quote", true),
    description: t("swirling_swarm_desc", true),
    source: t("swirling_swarm_source", true),
    applicableTo: ["Dancer", "Fury", "Sharpshooter"],
    book: "high",
  },
  {
    name: t("tabula_rasa", true),
    quote: t("tabula_rasa_quote", true),
    description: t("tabula_rasa_desc", true),
    source: t("tabula_rasa_source", true),
    applicableTo: ["Commander"],
    book: "high",
  },
  {
    name: t("theme_song", true),
    quote: t("theme_song_quote", true),
    description: t("theme_song_desc", true),
    source: t("theme_song_source", true),
    applicableTo: ["Chanter"],
    book: "high",
  },
  {
    name: t("triple_slash", true),
    quote: t("triple_slash_quote", true),
    description: t("triple_slash_desc", true),
    source: t("triple_slash_source", true),
    applicableTo: ["Dancer", "Weaponmaster"],
    book: "high",
  },

  // FUTF - techno
  {
    name: t("arcane_soldier", true),
    quote: t("arcane_soldier_quote", true),
    description: t("arcane_soldier_desc", true),
    source: t("arcane_soldier_source", true),
    applicableTo: ["Elementalist", "Sharpshooter", "Weaponmaster"],
    book: "techno",
  },
  {
    name: t("brainwave_discharge", true),
    quote: t("brainwave_discharge_quote", true),
    description: t("brainwave_discharge_desc", true),
    source: t("brainwave_discharge_source", true),
    applicableTo: ["Esper"],
    book: "techno",
  },
  {
    name: t("bullet_time", true),
    quote: t("bullet_time_quote", true),
    description: t("bullet_time_desc", true),
    source: t("bullet_time_source", true),
    applicableTo: ["Entropist", "Rogue"],
    book: "techno",
  },
  {
    name: t("decoy_bait", true),
    quote: t("decoy_bait_quote", true),
    description: t("decoy_bait_desc", true),
    source: t("decoy_bait_source", true),
    applicableTo: ["Sharpshooter"],
    book: "techno",
  },
  {
    name: t("dreamslice", true),
    quote: t("dreamslice_quote", true),
    description: t("dreamslice_desc", true),
    source: t("dreamslice_source", true),
    applicableTo: ["Darkblade", "Esper"],
    book: "techno",
  },
  {
    name: t("dynamic_synchronization", true),
    quote: t("dynamic_synchronization_quote", true),
    description: t("dynamic_synchronization_desc", true),
    source: t("dynamic_synchronization_source", true),
    applicableTo: ["Pilot"],
    book: "techno",
  },
  {
    name: t("greater_akromorphosis", true),
    quote: t("greater_akromorphosis_quote", true),
    description: t("greater_akromorphosis_desc", true),
    source: t("greater_akromorphosis_source", true),
    applicableTo: ["Mutant"],
    book: "techno",
  },
  {
    name: t("greater_ecdysis", true),
    quote: t("greater_ecdysis_quote", true),
    description: t("greater_ecdysis_desc", true),
    source: t("greater_ecdysis_source", true),
    applicableTo: ["Mutant"],
    book: "techno",
  },
  {
    name: t("greater_theriomorphosis", true),
    quote: t("greater_theriomorphosis_quote", true),
    description: t("greater_theriomorphosis_desc", true),
    source: t("greater_theriomorphosis_source", true),
    applicableTo: [],
    book: "techno",
  },
  {
    name: t("hit_the_nerve", true),
    quote: t("hit_the_nerve_quote", true),
    description: t("hit_the_nerve_desc", true),
    source: t("hit_the_nerve_source", true),
    applicableTo: ["Chanter", "Orator"],
    book: "techno",
  },
  {
    name: t("make_it_or_break_it", true),
    quote: t("make_it_or_break_it_quote", true),
    description: t("make_it_or_break_it_desc", true),
    source: t("make_it_or_break_it_source", true),
    applicableTo: ["Darkblade", "Fury"],
    book: "techno",
  },
  {
    name: t("mimeoclepsis", true),
    quote: t("mimeoclepsis_quote", true),
    description: t("mimeoclepsis_desc", true),
    source: t("mimeoclepsis_source", true),
    applicableTo: ["Chimerist", "Mutant"],
    book: "techno",
  },
  {
    name: t("nebulization", true),
    quote: t("nebulization_quote", true),
    description: t("nebulization_desc", true),
    source: t("nebulization_source", true),
    applicableTo: ["Tinkerer"],
    book: "techno",
  },
  {
    name: t("overload_burst", true),
    quote: t("overload_burst_quote", true),
    description: t("overload_burst_desc", true),
    source: t("overload_burst_source", true),
    applicableTo: ["Pilot"],
    book: "techno",
  },
  {
    name: t("psychic_field", true),
    quote: t("psychic_field_quote", true),
    description: t("psychic_field_desc", true),
    source: t("psychic_field_source", true),
    applicableTo: ["Esper"],
    book: "techno",
  },
  {
    name: t("quantum_magicannon", true),
    quote: t("quantum_magicannon_quote", true),
    description: t("quantum_magicannon_desc", true),
    source: t("quantum_magicannon_source", true),
    applicableTo: ["Tinkerer"],
    book: "techno",
  },
  {
    name: t("quick_scan", true),
    quote: t("quick_scan_quote", true),
    description: t("quick_scan_desc", true),
    source: t("quick_scan_source", true),
    applicableTo: ["Loremaster"],
    book: "techno",
  },
  {
    name: t("steel_witch", true),
    quote: t("steel_witch_quote", true),
    description: t("steel_witch_desc", true),
    source: t("steel_witch_source", true),
    applicableTo: ["Pilot"],
    book: "techno",
  },

  // FUNF - natural
  {
    name: t("all_you_can_eat", true),
    quote: t("all_you_can_eat_quote", true),
    description: t("all_you_can_eat_desc", true),
    source: t("all_you_can_eat_source", true),
    applicableTo: ["Gourmet"],
    book: "natural",
  },
  {
    name: t("auramancer_s_refraction", true),
    quote: t("auramancer_s_refraction_quote", true),
    description: t("auramancer_s_refraction_desc", true),
    source: t("auramancer_s_refraction_source", true),
    applicableTo: ["Arcanist", "Spiritist"],
    book: "natural",
  },
  {
    name: t("bend_magic", true),
    quote: t("bend_magic_quote", true),
    description: t("bend_magic_desc", true),
    source: t("bend_magic_source", true),
    applicableTo: ["Elementalist", "Entropist", "Invoker", "Symbolist"],
    book: "natural",
  },
  {
    name: t("brambleheart", true),
    quote: t("brambleheart_quote", true),
    description: t("brambleheart_desc", true),
    source: t("brambleheart_source", true),
    applicableTo: ["Darkblade", "Floralist"],
    book: "natural",
  },
  {
    name: t("brave_bash", true),
    quote: t("brave_bash_quote", true),
    description: t("brave_bash_desc", true),
    source: t("brave_bash_source", true),
    applicableTo: ["Commander", "Guardian", "Weaponmaster"],
    book: "natural",
  },
  {
    name: t("cheer_up", true),
    quote: t("cheer_up_quote", true),
    description: t("cheer_up_desc", true),
    source: t("cheer_up_source", true),
    applicableTo: ["Chanter", "Esper", "Orator"],
    book: "natural",
  },
  {
    name: t("chimeric_soul", true),
    quote: t("chimeric_soul_quote", true),
    description: t("chimeric_soul_desc", true),
    source: t("chimeric_soul_source", true),
    applicableTo: ["Chimerist", "Mutant"],
    book: "natural",
  },
  {
    name: t("cleansing_moonlight", true),
    quote: t("cleansing_moonlight_quote", true),
    description: t("cleansing_moonlight_desc", true),
    source: t("cleansing_moonlight_source", true),
    applicableTo: ["Entropist", "Spiritist"],
    book: "natural",
  },
  {
    name: t("ephemeral_tranquility", true),
    quote: t("ephemeral_tranquility_quote", true),
    description: t("ephemeral_tranquility_desc", true),
    source: t("ephemeral_tranquility_source", true),
    applicableTo: ["Dancer", "Esper", "Rogue", "Spiritist", "Symbolist"],
    book: "natural",
  },
  {
    name: t("fitcast", true),
    quote: t("fitcast_quote", true),
    description: t("fitcast_desc", true),
    source: t("fitcast_source", true),
    applicableTo: ["Chimerist", "Darkblade", "Esper", "Fury", "Wayfarer"],
    book: "natural",
  },
  {
    name: t("for_a_better_future", true),
    quote: t("for_a_better_future_quote", true),
    description: t("for_a_better_future_desc", true),
    source: t("for_a_better_future_source", true),
    applicableTo: ["Merchant"],
    book: "natural",
  },
  {
    name: t("greater_chloromancy", true),
    quote: t("greater_chloromancy_quote", true),
    description: t("greater_chloromancy_desc", true),
    source: t("greater_chloromancy_source", true),
    applicableTo: ["Floralist"],
    book: "natural",
  },
  {
    name: t("green_thumb", true),
    quote: t("green_thumb_quote", true),
    description: t("green_thumb_desc", true),
    source: t("green_thumb_source", true),
    applicableTo: ["Floralist"],
    book: "natural",
  },
  {
    name: t("inner_wellspring", true),
    quote: t("inner_wellspring_quote", true),
    description: t("inner_wellspring_desc", true),
    source: t("inner_wellspring_source", true),
    applicableTo: ["Invoker"],
    book: "natural",
  },
  {
    name: t("power_nap", true),
    quote: t("power_nap_quote", true),
    description: t("power_nap_desc", true),
    source: t("power_nap_source", true),
    applicableTo: ["Guardian", "Merchant", "Wayfarer"],
    book: "natural",
  },
  {
    name: t("side_by_side", true),
    quote: t("side_by_side_quote", true),
    description: t("side_by_side_desc", true),
    source: t("side_by_side_source", true),
    applicableTo: ["Wayfarer"],
    book: "natural",
  },
  {
    name: t("silent_hunter", true),
    quote: t("silent_hunter_quote", true),
    description: t("silent_hunter_desc", true),
    source: t("silent_hunter_source", true),
    applicableTo: ["Rogue", "Sharpshooter", "Weaponmaster"],
    book: "natural",
  },
  {
    name: t("skillful_dosage", true),
    quote: t("skillful_dosage_quote", true),
    description: t("skillful_dosage_desc", true),
    source: t("skillful_dosage_source", true),
    applicableTo: ["Gourmet", "Loremaster", "Merchant", "Tinkerer"],
    book: "natural",
  },
  {
    name: t("specialty_of_the_house", true),
    quote: t("specialty_of_the_house_quote", true),
    description: t("specialty_of_the_house_desc", true),
    source: t("specialty_of_the_house_source", true),
    applicableTo: ["Gourmet"],
    book: "natural",
  },
  {
    name: t("strength_of_five_wellsprings", true),
    quote: t("strength_of_five_wellsprings_quote", true),
    description: t("strength_of_five_wellsprings_desc", true),
    source: t("strength_of_five_wellsprings_source", true),
    applicableTo: ["Invoker"],
    book: "natural",
  },
  {
    name: t("wise_counsel", true),
    quote: t("wise_counsel_quote", true),
    description: t("wise_counsel_desc", true),
    source: t("wise_counsel_source", true),
    applicableTo: ["Commander", "Loremaster", "Orator"],
    book: "natural",
  },

  // FUBC - bonus
  {
    name: t("anatomist", true),
    quote: t("anatomist_quote", true),
    description: t("anatomist_desc", true),
    source: t("anatomist_source", true),
    applicableTo: ["Fury", "Loremaster", "Sharpshooter"],
    book: "bonus",
  },
  {
    name: t("arcane_sacrifice", true),
    quote: t("arcane_sacrifice_quote", true),
    description: t("arcane_sacrifice_desc", true),
    source: t("arcane_sacrifice_source", true),
    applicableTo: ["Arcanist", "Guardian"],
    book: "bonus",
  },
  {
    name: t("birth_of_the_cruel", true),
    quote: t("birth_of_the_cruel_quote", true),
    description: t("birth_of_the_cruel_desc", true),
    source: t("birth_of_the_cruel_source", true),
    applicableTo: ["Necromancer"],
    book: "bonus",
  },
  {
    name: t("black_white", true),
    quote: t("black_white_quote", true),
    description: t("black_white_desc", true),
    source: t("black_white_source", true),
    applicableTo: ["Ace of Cards", "Darkblade", "Entropist", "Spiritist"],
    book: "bonus",
  },
  {
    name: t("broken_wing_tactic", true),
    quote: t("broken_wing_tactic_quote", true),
    description: t("broken_wing_tactic_desc", true),
    source: t("broken_wing_tactic_source", true),
    applicableTo: ["Commander", "Guardian"],
    book: "bonus",
  },
  {
    name: t("card_vanguard", true),
    quote: t("card_vanguard_quote", true),
    description: t("card_vanguard_desc", true),
    source: t("card_vanguard_source", true),
    applicableTo: ["Ace of Cards"],
    book: "bonus",
  },
  {
    name: t("duel_master", true),
    quote: t("duel_master_quote", true),
    description: t("duel_master_desc", true),
    source: t("duel_master_source", true),
    applicableTo: [
      "Ace of Cards",
      "Fury",
      "Rogue",
      "Sharpshooter",
      "Weaponmaster",
    ],
    book: "bonus",
  },
  {
    name: t("flow_of_yin_and_yang", true),
    quote: t("flow_of_yin_and_yang_quote", true),
    description: t("flow_of_yin_and_yang_desc", true),
    source: t("flow_of_yin_and_yang_source", true),
    applicableTo: ["Dancer", "Elementalist", "Esper", "Invoker"],
    book: "bonus",
  },
  {
    name: t("forbidden_rite", true),
    quote: t("forbidden_rite_quote", true),
    description: t("forbidden_rite_desc", true),
    source: t("forbidden_rite_source", true),
    applicableTo: ["Ace of Cards", "Arcanist"],
    book: "bonus",
  },
  {
    name: t("great_cauldron_s_secret", true),
    quote: t("great_cauldron_s_secret_quote", true),
    description: t("great_cauldron_s_secret_desc", true),
    source: t("great_cauldron_s_secret_source", true),
    applicableTo: ["Tinkerer"],
    book: "bonus",
  },
  {
    name: t("harvester_of_sorrow", true),
    quote: t("harvester_of_sorrow_quote", true),
    description: t("harvester_of_sorrow_desc", true),
    source: t("harvester_of_sorrow_source", true),
    applicableTo: ["Entropist", "Necromancer"],
    book: "bonus",
  },
  {
    name: t("hunter_s_trick", true),
    quote: t("hunter_s_trick_quote", true),
    description: t("hunter_s_trick_desc", true),
    source: t("hunter_s_trick_source", true),
    applicableTo: ["Sharpshooter", "Weaponmaster"],
    book: "bonus",
  },
  {
    name: t("impaler_dragon", true),
    quote: t("impaler_dragon_quote", true),
    description: t("impaler_dragon_desc", true),
    source: t("impaler_dragon_source", true),
    applicableTo: ["Commander", "Darkblade"],
    book: "bonus",
  },
  {
    name: t("it_lives", true),
    quote: t("it_lives_quote", true),
    description: t("it_lives_desc", true),
    source: t("it_lives_source", true),
    applicableTo: ["Tinkerer", "Wayfarer"],
    book: "bonus",
  },
  {
    name: t("like_an_open_book", true),
    quote: t("like_an_open_book_quote", true),
    description: t("like_an_open_book_desc", true),
    source: t("like_an_open_book_source", true),
    applicableTo: ["Esper", "Loremaster", "Rogue"],
    book: "bonus",
  },
  {
    name: t("nether_slash", true),
    quote: t("nether_slash_quote", true),
    description: t("nether_slash_desc", true),
    source: t("nether_slash_source", true),
    applicableTo: ["Darkblade", "Elementalist", "Pilot"],
    book: "bonus",
  },
  {
    name: t("ofuda_mastery", true),
    quote: t("ofuda_mastery_quote", true),
    description: t("ofuda_mastery_desc", true),
    source: t("ofuda_mastery_source", true),
    applicableTo: ["Arcanist", "Merchant", "Symbolist", "Spiritist"],
    book: "bonus",
  },
  {
    name: t("phagomagus", true),
    quote: t("phagomagus_quote", true),
    description: t("phagomagus_desc", true),
    source: t("phagomagus_source", true),
    applicableTo: ["Chimerist", "Entropist", "Gourmet", "Mutant"],
    book: "bonus",
  },
  {
    name: t("pulse_of_the_maggots", true),
    quote: t("pulse_of_the_maggots_quote", true),
    description: t("pulse_of_the_maggots_desc", true),
    source: t("pulse_of_the_maggots_source", true),
    applicableTo: ["Necromancer"],
    book: "bonus",
  },
  {
    name: t("symbiotic_roots", true),
    quote: t("symbiotic_roots_quote", true),
    description: t("symbiotic_roots_desc", true),
    source: t("symbiotic_roots_source", true),
    applicableTo: ["Chimerist", "Floralist", "Mutant", "Wayfarer"],
    book: "bonus",
  },
  {
    name: t("witchvoice", true),
    quote: t("witchvoice_quote", true),
    description: t("witchvoice_desc", true),
    source: t("witchvoice_source", true),
    applicableTo: ["Chanter", "Orator"],
    book: "bonus",
  },
];

export default heroics;
