import { t } from "../translation/translate";
import { slugify } from "./slugify";

export const npcAttacks = [
  {
    fuid: "staff",
    itemType: "basic",
    category: t("Arcane", true),
    name: t("Staff", true),
    cost: 100,
    accuracy: { attr1: "will", attr2: "will", value: 0, defense: "def" },
    damage: { value: 1, type: "physical", hrZero: false },
    hands: 2,
    range: "melee",
    martial: false,
  },
  {
    fuid: "tome",
    itemType: "basic",
    category: t("Arcane", true),
    name: t("Tome", true),
    cost: 100,
    accuracy: { attr1: "insight", attr2: "insight", value: 0, defense: "def" },
    damage: { value: 1, type: "physical", hrZero: false },
    hands: 2,
    range: "melee",
    martial: false,
  },
  {
    fuid: "crossbow",
    itemType: "basic",
    category: t("Bow", true),
    name: t("Crossbow", true),
    cost: 150,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 0,
      defense: "def",
    },
    damage: { value: 3, type: "physical", hrZero: false },
    hands: 2,
    range: "ranged",
    martial: false,
  },
  {
    fuid: "shortbow",
    itemType: "basic",
    category: t("Bow", true),
    name: t("Shortbow", true),
    cost: 200,
    accuracy: {
      attr1: "dexterity",
      attr2: "dexterity",
      value: 0,
      defense: "def",
    },
    damage: { value: 3, type: "physical", hrZero: false },
    hands: 2,
    range: "ranged",
    martial: false,
  },
  {
    fuid: "chain-whip",
    itemType: "basic",
    category: t("Flail", true),
    name: t("Chain Whip", true),
    cost: 150,
    accuracy: {
      attr1: "dexterity",
      attr2: "dexterity",
      value: 0,
      defense: "def",
    },
    damage: { value: 3, type: "physical", hrZero: false },
    hands: 2,
    range: "melee",
    martial: false,
  },
  {
    fuid: "pistol",
    itemType: "basic",
    category: t("Firearm", true),
    name: t("Pistol", true),
    cost: 250,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 0,
      defense: "def",
    },
    damage: { value: 3, type: "physical", hrZero: false },
    hands: 1,
    range: "ranged",
    martial: true,
  },
  {
    fuid: "light-spear",
    itemType: "basic",
    category: t("Spear", true),
    name: t("Light Spear", true),
    cost: 200,
    accuracy: { attr1: "dexterity", attr2: "might", value: 0, defense: "def" },
    damage: { value: 3, type: "physical", hrZero: false },
    hands: 1,
    range: "melee",
    martial: true,
  },
  {
    fuid: "heavy-spear",
    itemType: "basic",
    category: t("Spear", true),
    name: t("Heavy Spear", true),
    cost: 200,
    accuracy: { attr1: "dexterity", attr2: "might", value: 0, defense: "def" },
    damage: { value: 7, type: "physical", hrZero: false },
    hands: 2,
    range: "melee",
    martial: true,
  },
  {
    fuid: "shuriken",
    itemType: "basic",
    category: t("Thrown", true),
    name: t("Shuriken", true),
    cost: 150,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 0,
      defense: "def",
    },
    damage: { value: -1, type: "physical", hrZero: false },
    hands: 1,
    range: "ranged",
    martial: false,
  },
  {
    fuid: "iron-hammer",
    itemType: "basic",
    category: t("Heavy", true),
    name: t("Iron Hammer", true),
    cost: 200,
    accuracy: { attr1: "might", attr2: "might", value: 0, defense: "def" },
    damage: { value: 1, type: "physical", hrZero: false },
    hands: 1,
    range: "melee",
    martial: false,
  },
  {
    fuid: "broadaxe",
    itemType: "basic",
    category: t("Heavy", true),
    name: t("Broadaxe", true),
    cost: 250,
    accuracy: { attr1: "might", attr2: "might", value: 0, defense: "def" },
    damage: { value: 5, type: "physical", hrZero: false },
    hands: 1,
    range: "melee",
    martial: true,
  },
  {
    fuid: "waraxe",
    itemType: "basic",
    category: t("Heavy", true),
    name: t("Waraxe", true),
    cost: 250,
    accuracy: { attr1: "might", attr2: "might", value: 0, defense: "def" },
    damage: { value: 9, type: "physical", hrZero: false },
    hands: 2,
    range: "melee",
    martial: true,
  },
  {
    fuid: "steel-dagger",
    itemType: "basic",
    category: t("Dagger", true),
    name: t("Steel Dagger", true),
    cost: 150,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 1,
      defense: "def",
    },
    damage: { value: -1, type: "physical", hrZero: false },
    hands: 1,
    range: "melee",
    martial: false,
  },
  {
    fuid: "iron-knuckle",
    itemType: "basic",
    category: t("Brawling", true),
    name: t("Iron Knuckle", true),
    cost: 150,
    accuracy: { attr1: "dexterity", attr2: "might", value: 0, defense: "def" },
    damage: { value: 1, type: "physical", hrZero: false },
    hands: 1,
    range: "melee",
    martial: false,
  },
  {
    fuid: "katana",
    itemType: "basic",
    category: t("Sword", true),
    name: t("Katana", true),
    cost: 200,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 1,
      defense: "def",
    },
    damage: { value: 5, type: "physical", hrZero: false },
    hands: 2,
    range: "melee",
    martial: true,
  },
  {
    fuid: "bronze-sword",
    itemType: "basic",
    category: t("Sword", true),
    name: t("Bronze Sword", true),
    cost: 200,
    accuracy: { attr1: "dexterity", attr2: "might", value: 1, defense: "def" },
    damage: { value: 1, type: "physical", hrZero: false },
    hands: 1,
    range: "melee",
    martial: true,
  },
  {
    fuid: "greatsword",
    itemType: "basic",
    category: t("Sword", true),
    name: t("Greatsword", true),
    cost: 200,
    accuracy: { attr1: "dexterity", attr2: "might", value: 1, defense: "def" },
    damage: { value: 5, type: "physical", hrZero: false },
    hands: 2,
    range: "melee",
    martial: true,
  },
  {
    fuid: "rapier",
    itemType: "basic",
    category: t("Sword", true),
    name: t("Rapier", true),
    cost: 200,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 1,
      defense: "def",
    },
    damage: { value: 1, type: "physical", hrZero: false },
    hands: 1,
    range: "melee",
    martial: true,
  },
];



npcAttacks.forEach((item) => {
  if (item.fuid === undefined && item.name) item.fuid = slugify(item.name);
});

export default npcAttacks;
