import { t } from "../translation/translate";
import { slugify } from "./slugify";

export const npcSpells = [
  {
    fuid: "area-status",
    itemType: "spell",
    spellType: "npc",
    name: t("Area Status", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: false,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 0,
    targetDescription: t("Special"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("AreaStatus_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "breath",
    itemType: "spell",
    spellType: "npc",
    name: t("Breath", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: true,
    damage: { value: 10, type: "untyped", hrZero: false },
    cost: { resource: "mp", amount: 5, perTarget: false },
    maxTargets: 1,
    targetDescription: t("One creature"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("Breath_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "curse",
    itemType: "spell",
    spellType: "npc",
    name: t("Curse", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: true,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 5, perTarget: false },
    maxTargets: 1,
    targetDescription: t("One creature"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("Curse_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "curse-xl",
    itemType: "spell",
    spellType: "npc",
    name: t("Curse XL", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: true,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: t("One creature"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("CurseXL_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "cursed-breath",
    itemType: "spell",
    spellType: "npc",
    name: t("Cursed Breath", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: true,
    damage: { value: 15, type: "untyped", hrZero: false },
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: t("One creature"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("CursedBreath_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: " ",
    itemType: "spell",
    spellType: "npc",
    name: t("Devastation", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: false,
    damage: { value: 30, type: "untyped", hrZero: false },
    cost: { resource: "mp", amount: 30, perTarget: false },
    maxTargets: 0,
    targetDescription: t("Special"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("Devastation_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "lick-wounds",
    itemType: "spell",
    spellType: "npc",
    name: t("Lick Wounds", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: false,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 5, perTarget: false },
    maxTargets: 1,
    targetDescription: t("Self"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("LickWounds_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "life-theft",
    itemType: "spell",
    spellType: "npc",
    name: t("Life Theft", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: true,
    damage: { value: 15, type: "untyped", hrZero: false },
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: t("One creature"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("LifeTheft_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "mind-theft",
    itemType: "spell",
    spellType: "npc",
    name: t("Mind Theft", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: true,
    damage: { value: 15, type: "untyped", hrZero: false },
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: t("One creature"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("MindTheft_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "poison",
    itemType: "spell",
    spellType: "npc",
    name: t("Poison", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: true,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: t("Up to three creatures"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("Poison_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "quicken",
    itemType: "spell",
    spellType: "npc",
    name: t("Quicken", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: false,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 20, perTarget: false },
    maxTargets: 1,
    targetDescription: t("One creature"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("Quicken_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "rage",
    itemType: "spell",
    spellType: "npc",
    name: t("Rage", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: true,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: t("Up to three creatures"),
    duration: t("Instantaneous"),
    range: "ranged",
    effect: t("Rage_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "shell",
    itemType: "spell",
    spellType: "npc",
    name: t("Shell", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: false,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: t("Self"),
    duration: t("Scene"),
    range: "ranged",
    effect: t("Shell_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "war-cry",
    itemType: "spell",
    spellType: "npc",
    name: t("War Cry", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: false,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 10, perTarget: true },
    maxTargets: 3,
    targetDescription: t("Up to three creatures"),
    duration: t("Scene"),
    range: "ranged",
    effect: t("WarCry_desc", true),
    special: [],
    description: "",
  },
  {
    fuid: "weaken",
    itemType: "spell",
    spellType: "npc",
    name: t("Weaken", true),
    accuracy: { attr1: "insight", attr2: "will", value: 0, defense: "mdef" },
    isOffensive: true,
    damage: { value: 0, type: "physical", hrZero: false },
    cost: { resource: "mp", amount: 10, perTarget: false },
    maxTargets: 1,
    targetDescription: t("One creature"),
    duration: t("Scene"),
    range: "ranged",
    effect: t("Weaken_desc", true),
    special: [],
    description: "",
  },
];



npcSpells.forEach((item) => {
  if (item.fuid === undefined && item.name) item.fuid = slugify(item.name);
});
