import { t } from "../translation/translate";

export const npcSpells = [
  {
    itemType: "spell",
    name: t("Area Status", true),
    attr1: "insight",
    attr2: "will",
    type: "",
    damagetype: "physical",
    mp: "20",
    maxTargets: 0,
    target: t("Special"),
    duration: t("Instantaneous"),
    effect: t("AreaStatus_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Breath", true),
    attr1: "insight",
    attr2: "will",
    type: "offensive",
    damagetype: "physical",
    mp: "20",
    maxTargets: 1,
    target: t("One creature"),
    duration: t("Instantaneous"),
    effect: t("Breath_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Curse", true),
    attr1: "insight",
    attr2: "will",
    type: "offensive",
    damagetype: "physical",
    mp: "5",
    maxTargets: 1,
    target: t("One creature"),
    duration: t("Instantaneous"),
    effect: t("Curse_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Curse XL", true),
    attr1: "insight",
    attr2: "will",
    type: "offensive",
    damagetype: "physical",
    mp: "10",
    maxTargets: 1,
    target: t("One creature"),
    duration: t("Instantaneous"),
    effect: t("CurseXL_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Cursed Breath", true),
    attr1: "insight",
    attr2: "will",
    type: "offensive",
    damagetype: "physical",
    mp: "10",
    maxTargets: 1,
    target: t("One creature"),
    duration: t("Instantaneous"),
    effect: t("CursedBreath_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Devastation", true),
    attr1: "insight",
    attr2: "will",
    type: "",
    damagetype: "physical",
    mp: "30",
    maxTargets: 0,
    target: t("Special"),
    duration: t("Instantaneous"),
    effect: t("Devastation_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Lick Wounds", true),
    attr1: "insight",
    attr2: "will",
    type: "",
    damagetype: "physical",
    mp: "5",
    maxTargets: 1,
    target: t("Self"),
    duration: t("Instantaneous"),
    effect: t("LickWounds_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Life Theft", true),
    attr1: "insight",
    attr2: "will",
    type: "offensive",
    damagetype: "physical",
    mp: "10",
    maxTargets: 1,
    target: t("One creature"),
    duration: t("Instantaneous"),
    effect: t("LifeTheft_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Mind Theft", true),
    attr1: "insight",
    attr2: "will",
    type: "offensive",
    damagetype: "physical",
    mp: "10",
    maxTargets: 1,
    target: t("One creature"),
    duration: t("Instantaneous"),
    effect: t("MindTheft_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Poison", true),
    attr1: "insight",
    attr2: "will",
    type: "offensive",
    damagetype: "physical",
    mp: "10",
    maxTargets: 3,
    target: t("Up to three creatures"),
    duration: t("Instantaneous"),
    effect: t("Poison_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Quicken", true),
    attr1: "insight",
    attr2: "will",
    type: "",
    damagetype: "physical",
    mp: "20",
    maxTargets: 1,
    target: t("One creature"),
    duration: t("Instantaneous"),
    effect: t("Quicken_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Rage", true),
    attr1: "insight",
    attr2: "will",
    type: "offensive",
    damagetype: "physical",
    mp: "10",
    maxTargets: 3,
    target: t("Up to three creatures"),
    duration: t("Instantaneous"),
    effect: t("Rage_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Shell", true),
    attr1: "insight",
    attr2: "will",
    type: "",
    damagetype: "physical",
    mp: "10",
    maxTargets: 1,
    target: t("Self"),
    duration: t("Scene"),
    effect: t("Shell_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("War Cry", true),
    attr1: "insight",
    attr2: "will",
    type: "",
    damagetype: "physical",
    mp: "10",
    maxTargets: 3,
    target: t("Up to three creatures"),
    duration: t("Scene"),
    effect: t("WarCry_desc", true),
    special: []
  },
  {
    itemType: "spell",
    name: t("Weaken", true),
    attr1: "insight",
    attr2: "will",
    type: "offensive",
    damagetype: "physical",
    mp: "10",
    maxTargets: 1,
    target: t("One creature"),
    duration: t("Scene"),
    effect: t("Weaken_desc", true),
    special: []
  },
];
