// Available module types (slot is determined by type)
export const moduleTypes = [
  "pilot_module_armor",
  "pilot_module_weapon", 
  "pilot_module_support"
];

// Available vehicle frames
export const availableFrames = [
  {
    name: "pilot_frame_exoskeleton",
    description: "pilot_frame_exoskeleton_desc",
    passengers: 0,
    distance: 1,
    limits: {
      weapon: 2,
      armor: 1,
      support: -1,
    },
  },
  {
    name: "pilot_frame_mecha", 
    description: "pilot_frame_mecha_desc",
    passengers: 0,
    distance: 2,
    limits: {
      weapon: 2,
      armor: 1,
      support: -1,
    },
  },
  {
    name: "pilot_frame_steed",
    description: "pilot_frame_steed_desc",
    passengers: 1,
    distance: 2,
    limits: {
      weapon: 1,
      armor: 1,
      support: -1,
    },
  },
];

// Available modules organized by slot type
export const availableModules = {
  // ARMOR MODULES - Occupy armor slot
  armor: [
    {
      name: "pilot_module_flexible_plating",
      type: "pilot_module_armor",
      cost: 500,
      def: 2,
      mdef: 1,
      martial: false,
      category: "Armor",
    },
    {
      name: "pilot_module_heavy_plating",
      type: "pilot_module_armor", 
      cost: 500,
      def: 12,
      mdef: 8,
      martial: true,
      category: "Armor",
    },
    {
      name: "pilot_module_runic_plating",
      type: "pilot_module_armor",
      slot: "pilot_slot_armor", 
      cost: 500,
      def: 10,
      mdef: 11,
      martial: true,
      category: "Armor",
    },
    {
      name: "pilot_module_standard_plating",
      type: "pilot_module_armor",
      cost: 500,
      def: 11,
      mdef: 10,
      martial: true,
      category: "Armor",
    },
    {
      name: "pilot_custom_armor",
      type: "pilot_module_armor",
      description: "",
      customName: "",
      cost: 500,
      def: 0,
      mdef: 0,
      martial: false,
      category: "Armor",
    },
  ],
  
  // WEAPON MODULES - All weapon types
  weapon: [
    // Weapons
    {
      name: "pilot_module_arcane",
      type: "pilot_module_weapon",
      cumbersome: false,
      quality: "",
      category: "Arcane",
      cost: 500,
      prec: 0,
      damage: 8,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "will",
    },
    {
      name: "pilot_module_axe",
      type: "pilot_module_weapon",
      cumbersome: false,
      category: "Heavy",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 0,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_blade", 
      type: "pilot_module_weapon",
      cumbersome: false,
      category: "Dagger",
      quality: "",
      cost: 500,
      prec: 1,
      damage: 6,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_bow",
      type: "pilot_module_weapon",
      cumbersome: true,
      quality: "",
      category: "Bow",
      cost: 500,
      prec: 1,
      damage: 12,
      range: "Ranged",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_cannon",
      type: "pilot_module_weapon",
      cumbersome: true,
      category: "Firearm",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 14,
      range: "Ranged",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_claw",
      type: "pilot_module_weapon",
       description: "pilot_module_claw_desc",
      cumbersome: false,
      category: "Brawling",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 8,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_claymore",
      type: "pilot_module_weapon",
      cumbersome: true,
      category: "Sword",
      quality: "",
      cost: 500,
      prec: 1,
      damage: 14,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_esoteric",
      type: "pilot_module_weapon",
      cumbersome: true,
      category: "Sword",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 12,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "will",
    },
    {
      name: "pilot_module_flail",
      type: "pilot_module_weapon",
      cumbersome: false,
      category: "Flail",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 10,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_flamer",
      type: "pilot_module_weapon",
      cumbersome: false,
      category: "Firearm",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 10,
      range: "Melee",
      damageType: "Fire",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_machine_gun",
      type: "pilot_module_weapon",
      description: "pilot_module_machine_gun_desc",
      cumbersome: false,
      category: "Firearm",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 10,
      range: "Ranged",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_rifle",
      type: "pilot_module_weapon",
      cumbersome: false,
      category: "Firearm",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 10,
      range: "Ranged",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_scythe",
      type: "pilot_module_weapon",
      cumbersome: true,
      category: "Heavy",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 16,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    // Shield Module (now a weapon with shield flag)
    {
      name: "pilot_module_shield",
      type: "pilot_module_weapon",
      description: "pilot_module_shield_desc",
      category: "Brawling",
      isShield: true,
      quality: "",
      cost: 0,
      prec: 0,
      damage: 0,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "might",
      att2: "might",
    },
    {
      name: "pilot_module_spear",
      type: "pilot_module_weapon",
      cumbersome: false,
      category: "Spear",
      quality: "",
      cost: 500,
      prec: 0,
      damage: 10,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_sword",
      type: "pilot_module_weapon",
      cumbersome: false,
      category: "Sword",
      quality: "",
      cost: 500,
      prec: 1,
      damage: 8,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    {
      name: "pilot_module_trident",
      type: "pilot_module_weapon",
      cumbersome: true,
      category: "Spear",
      quality: "",
      cost: 500,
      prec: 1,
      damage: 14,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      att1: "dexterity",
      att2: "insight",
    },
    // Custom Weapon Module
    {
      name: "pilot_custom_weapon",
      type: "pilot_module_weapon",
      quality: "",
      category: "Heavy",
      cost: 0,
      prec: 0,
      damage: 0,
      range: "Melee",
      damageType: "Physical",
      qualityCost: 0,
      equipped: false,
      equippedSlot: "main",
      att1: "might",
      att2: "dexterity",
    },
  ],
  
  // SUPPORT MODULES - Special vehicle systems
  support: [
    {
      name: "pilot_custom_support",
      type: "pilot_module_support",
      description: "",
      customName: "",
      isComplex: false
    },
    {
      name: "pilot_module_aerial",
      type: "pilot_module_support",
      description: "pilot_module_aerial_desc",
      isComplex: true
    },
    {
      name: "pilot_module_anti-element",
      type: "pilot_module_support", 
      description: "pilot_module_anti-element_desc",
      isComplex: false
    },
    {
      name: "pilot_module_advanced_targeting",
      type: "pilot_module_support",
      description: "pilot_module_advanced_targeting_desc",
      isComplex: false
    },
    {
      name: "pilot_module_counterstrike",
      type: "pilot_module_support",
      description: "pilot_module_counterstrike_desc",
      isComplex: false
    },
    {
      name: "pilot_module_excavation",
      type: "pilot_module_support",
      description: "pilot_module_excavation_desc",
      isComplex: false
    },
    {
      name: "pilot_module_expanded_plating",
      type: "pilot_module_support",
      description: "pilot_module_expanded_plating_desc",
      isComplex: false
    },
    {
      name: "pilot_module_magistatic",
      type: "pilot_module_support",
      description: "pilot_module_magistatic_desc",
      isComplex: false
    },
      {
      name: "pilot_module_power",
      type: "pilot_module_support",
      description: "pilot_module_power_desc",
      isComplex: false
    },
      {
      name: "pilot_module_rapid_interface",
      type: "pilot_module_support",
      description: "pilot_module_rapid_interface_desc",
      isComplex: false
    },
      {
      name: "pilot_module_seafarer",
      type: "pilot_module_support",
      description: "pilot_module_seafarer_desc",
      isComplex: false
    },
      {
      name: "pilot_module_seat",
      type: "pilot_module_support",
      description: "pilot_module_seat_desc",
      isComplex: false
    },
    {
      name: "pilot_module_secondary_offensive",
      type: "pilot_module_support",
      description: "pilot_module_secondary_offensive_desc",
      isComplex: false
    },
    {
      name: "pilot_module_sensor",
      type: "pilot_module_support",
      description: "pilot_module_sensor_desc",
      isComplex: false
    },
    {
      name: "pilot_module_turbo",
      type: "pilot_module_support",
      description: "pilot_module_turbo_desc",
      isComplex: false
    },
  ],
};