const weapons = [
  {
    fuid: "unarmed-strike",
    category: "Brawling",
    name: "Unarmed Strike",
    cost: 0,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 0,
    type: "physical",
    hands: 1,
    melee: true,
    martial: false,
  },
  {
    fuid: "staff",
    category: "Arcane",
    name: "Staff",
    cost: 100,
    att1: "will",
    att2: "will",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    melee: true,
    martial: false,
  },
  {
    fuid: "tome",
    category: "Arcane",
    name: "Tome",
    cost: 100,
    att1: "insight",
    att2: "insight",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    melee: true,
    martial: false,
  },
  {
    fuid: "crossbow",
    category: "Bow",
    name: "Crossbow",
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    ranged: true,
    martial: false,
  },
  {
    fuid: "shortbow",
    category: "Bow",
    name: "Shortbow",
    cost: 200,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    ranged: true,
    martial: false,
  },
  {
    fuid: "chain-whip",
    category: "Flail",
    name: "Chain Whip",
    cost: 150,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    melee: true,
    martial: false,
  },
  {
    fuid: "pistol",
    category: "Firearm",
    name: "Pistol",
    cost: 250,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    ranged: true,
    martial: true,
  },
  {
    fuid: "light-spear",
    category: "spear_category",
    name: "Light Spear",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    melee: true,
    martial: true,
  },
  {
    fuid: "heavy-spear",
    category: "spear_category",
    name: "Heavy Spear",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 12,
    type: "physical",
    hands: 2,
    melee: true,
    martial: true,
  },
  {
    fuid: "shuriken",
    category: "Thrown",
    name: "Shuriken",
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 4,
    type: "physical",
    hands: 1,
    ranged: true,
    martial: false,
  },
  {
    fuid: "iron-hammer",
    category: "Heavy",
    name: "Iron Hammer",
    cost: 200,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
    martial: false,
  },
  {
    fuid: "broadaxe",
    category: "Heavy",
    name: "Broadaxe",
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 10,
    type: "physical",
    hands: 1,
    melee: true,
    martial: true,
  },
  {
    fuid: "waraxe",
    category: "Heavy",
    name: "Waraxe",
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 14,
    type: "physical",
    hands: 2,
    melee: true,
    martial: true,
  },
  {
    fuid: "steel-dagger",
    category: "Dagger",
    name: "Steel Dagger",
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 4,
    type: "physical",
    hands: 1,
    melee: true,
    martial: false,
  },
  {
    fuid: "iron-knuckle",
    category: "Brawling",
    name: "Iron Knuckle",
    cost: 150,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
    martial: false,
  },
  {
    fuid: "katana",
    category: "Sword",
    name: "Katana",
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    melee: true,
    martial: true,
  },
  {
    fuid: "bronze-sword",
    category: "Sword",
    name: "Bronze Sword",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
    martial: true,
  },
  {
    fuid: "greatsword",
    category: "Sword",
    name: "Greatsword",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    melee: true,
    martial: true,
  },
  {
    fuid: "rapier",
    category: "Sword",
    name: "Rapier",
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
    martial: true,
  },
];

const slugify = (value = "") =>
  String(value)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

weapons.forEach((item) => {
  if (item.fuid === undefined && item.name) item.fuid = slugify(item.name);
});

export default weapons;
