const weapons = [
  {
    fuid: "unarmed-strike",
    itemType: "weapon",
    category: "Brawling",
    name: "Unarmed Strike",
    cost: 0,
    accuracy: { attr1: "dexterity", attr2: "might", value: 0, defense: "def" },
    damage: { value: 0, type: "physical" },
    hands: 1,
    range: "melee",
    martial: false,
  },
  {
    fuid: "staff",
    itemType: "weapon",
    category: "Arcane",
    name: "Staff",
    cost: 100,
    accuracy: { attr1: "will", attr2: "will", value: 0, defense: "def" },
    damage: { value: 6, type: "physical" },
    hands: 2,
    range: "melee",
    martial: false,
  },
  {
    fuid: "tome",
    itemType: "weapon",
    category: "Arcane",
    name: "Tome",
    cost: 100,
    accuracy: { attr1: "insight", attr2: "insight", value: 0, defense: "def" },
    damage: { value: 6, type: "physical" },
    hands: 2,
    range: "melee",
    martial: false,
  },
  {
    fuid: "crossbow",
    itemType: "weapon",
    category: "Bow",
    name: "Crossbow",
    cost: 150,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 0,
      defense: "def",
    },
    damage: { value: 8, type: "physical" },
    hands: 2,
    range: "ranged",
    martial: false,
  },
  {
    fuid: "shortbow",
    itemType: "weapon",
    category: "Bow",
    name: "Shortbow",
    cost: 200,
    accuracy: {
      attr1: "dexterity",
      attr2: "dexterity",
      value: 0,
      defense: "def",
    },
    damage: { value: 8, type: "physical" },
    hands: 2,
    range: "ranged",
    martial: false,
  },
  {
    fuid: "chain-whip",
    itemType: "weapon",
    category: "Flail",
    name: "Chain Whip",
    cost: 150,
    accuracy: {
      attr1: "dexterity",
      attr2: "dexterity",
      value: 0,
      defense: "def",
    },
    damage: { value: 8, type: "physical" },
    hands: 2,
    range: "melee",
    martial: false,
  },
  {
    fuid: "pistol",
    itemType: "weapon",
    category: "Firearm",
    name: "Pistol",
    cost: 250,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 0,
      defense: "def",
    },
    damage: { value: 8, type: "physical" },
    hands: 1,
    range: "ranged",
    martial: true,
  },
  {
    fuid: "light-spear",
    itemType: "weapon",
    category: "Spear",
    name: "Light Spear",
    cost: 200,
    accuracy: { attr1: "dexterity", attr2: "might", value: 0, defense: "def" },
    damage: { value: 8, type: "physical" },
    hands: 1,
    range: "melee",
    martial: true,
  },
  {
    fuid: "heavy-spear",
    itemType: "weapon",
    category: "Spear",
    name: "Heavy Spear",
    cost: 200,
    accuracy: { attr1: "dexterity", attr2: "might", value: 0, defense: "def" },
    damage: { value: 12, type: "physical" },
    hands: 2,
    range: "melee",
    martial: true,
  },
  {
    fuid: "shuriken",
    itemType: "weapon",
    category: "Thrown",
    name: "Shuriken",
    cost: 150,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 0,
      defense: "def",
    },
    damage: { value: 4, type: "physical" },
    hands: 1,
    range: "ranged",
    martial: false,
  },
  {
    fuid: "iron-hammer",
    itemType: "weapon",
    category: "Heavy",
    name: "Iron Hammer",
    cost: 200,
    accuracy: { attr1: "might", attr2: "might", value: 0, defense: "def" },
    damage: { value: 6, type: "physical" },
    hands: 1,
    range: "melee",
    martial: false,
  },
  {
    fuid: "broadaxe",
    itemType: "weapon",
    category: "Heavy",
    name: "Broadaxe",
    cost: 250,
    accuracy: { attr1: "might", attr2: "might", value: 0, defense: "def" },
    damage: { value: 10, type: "physical" },
    hands: 1,
    range: "melee",
    martial: true,
  },
  {
    fuid: "waraxe",
    itemType: "weapon",
    category: "Heavy",
    name: "Waraxe",
    cost: 250,
    accuracy: { attr1: "might", attr2: "might", value: 0, defense: "def" },
    damage: { value: 14, type: "physical" },
    hands: 2,
    range: "melee",
    martial: true,
  },
  {
    fuid: "steel-dagger",
    itemType: "weapon",
    category: "Dagger",
    name: "Steel Dagger",
    cost: 150,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 1,
      defense: "def",
    },
    damage: { value: 4, type: "physical" },
    hands: 1,
    range: "melee",
    martial: false,
  },
  {
    fuid: "iron-knuckle",
    itemType: "weapon",
    category: "Brawling",
    name: "Iron Knuckle",
    cost: 150,
    accuracy: { attr1: "dexterity", attr2: "might", value: 0, defense: "def" },
    damage: { value: 6, type: "physical" },
    hands: 1,
    range: "melee",
    martial: false,
  },
  {
    fuid: "katana",
    itemType: "weapon",
    category: "Sword",
    name: "Katana",
    cost: 200,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 1,
      defense: "def",
    },
    damage: { value: 10, type: "physical" },
    hands: 2,
    range: "melee",
    martial: true,
  },
  {
    fuid: "bronze-sword",
    itemType: "weapon",
    category: "Sword",
    name: "Bronze Sword",
    cost: 200,
    accuracy: { attr1: "dexterity", attr2: "might", value: 1, defense: "def" },
    damage: { value: 6, type: "physical" },
    hands: 1,
    range: "melee",
    martial: true,
  },
  {
    fuid: "greatsword",
    itemType: "weapon",
    category: "Sword",
    name: "Greatsword",
    cost: 200,
    accuracy: { attr1: "dexterity", attr2: "might", value: 1, defense: "def" },
    damage: { value: 10, type: "physical" },
    hands: 2,
    range: "melee",
    martial: true,
  },
  {
    fuid: "rapier",
    itemType: "weapon",
    category: "Sword",
    name: "Rapier",
    cost: 200,
    accuracy: {
      attr1: "dexterity",
      attr2: "insight",
      value: 1,
      defense: "def",
    },
    damage: { value: 6, type: "physical" },
    hands: 1,
    range: "melee",
    martial: true,
  },
];

export default weapons;
