import type { GroupLabels, ItemFieldConfig, FieldConfig } from "../fieldConfig";
import type { NpcSpell } from "../../../schema/itemSchemas/npcSpell";
import { metaFieldConfig } from "../metaFieldConfig";
import { typeOptions } from "../typeOptions";
import { DURATION_OPTIONS, TARGET_OPTIONS } from "./spells/options";
import { SHARED_LABEL_KEYS, prefixedLabel } from "./sharedLabelKeys";
import {
  makePassivesTabField,
  behaviorsTabField,
  behaviorGroupLabels,
  DEFAULT_ITEM_TABS,
} from "../shared/behaviorFields";
import { ITEM_SCOPED_KEYS } from "../shared/itemScopedKeys";

export type NpcSpellFormState = NpcSpell & Record<string, unknown>;
const NPC_SPELL_LABEL_PREFIX = "npc.spell";

export { DEFAULT_ITEM_TABS as npcSpellTabs };

const G = {
  core: "core",
  accuracy: "accuracy",
  damage: "damage",
  details: "details",
  effect: "effect",
} as const;

export const npcSpellGroupLabels: GroupLabels = {
  core: "section.core",
  accuracy: "section.accuracy",
  damage: "section.damage",
  details: "section.details",
  effect: "section.effect",
  meta: "section.meta",
  ...behaviorGroupLabels,
};

export const npcSpellFieldConfig: ItemFieldConfig<NpcSpellFormState> = [
  {
    key: "itemType",
    kind: "computed",
    label: "shared.itemType",
    defaultValue: "spell",
    group: G.core,
    order: 0,
  },
  {
    key: "fuid",
    kind: "editable",
    label: prefixedLabel(NPC_SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.fuid),
    component: "fuid",
    defaultValue: "",
    group: G.core,
    order: -1,
    gridSize: 12,
  },
  {
    key: "name",
    kind: "editable",
    label: prefixedLabel(NPC_SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.name),
    component: "text",
    defaultValue: "",
    group: G.core,
    order: 1,
    validationHints: { required: true },
    gridSize: "grow",
  },
  {
    key: "isOffensive",
    kind: "editable",
    label: prefixedLabel(NPC_SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.offensive),
    component: "offensive-toggle",
    defaultValue: false,
    group: G.core,
    order: 2,
    gridSize: "auto",
  },
  {
    key: "range",
    kind: "editable",
    label: "shared.range",
    component: "select",
    defaultValue: "ranged",
    group: G.core,
    order: 3,
    gridSize: 4,
    componentProps: {
      options: [
        { value: "melee", label: "Melee" },
        { value: "ranged", label: "Ranged" },
      ],
      disabled: true,
    },
  },
  {
    key: "accuracy.attr1",
    kind: "editable",
    label: "shared.accuracy.attr1",
    component: "select",
    defaultValue: "dexterity",
    group: G.accuracy,
    order: 10,
    gridSize: { xs: 6, md: 6 },
    dependencies: (s) => !!s.isOffensive,
    componentProps: {
      options: [
        { value: "dexterity", label: "DEX" },
        { value: "insight", label: "INS" },
        { value: "might", label: "MIG" },
        { value: "will", label: "WLP" },
      ],
    },
  },
  {
    key: "accuracy.attr2",
    kind: "editable",
    label: "shared.accuracy.attr2",
    component: "select",
    defaultValue: "dexterity",
    group: G.accuracy,
    order: 11,
    gridSize: { xs: 6, md: 6 },
    dependencies: (s) => !!s.isOffensive,
    componentProps: {
      options: [
        { value: "dexterity", label: "DEX" },
        { value: "insight", label: "INS" },
        { value: "might", label: "MIG" },
        { value: "will", label: "WLP" },
      ],
    },
  },
  {
    key: "accuracy.value",
    kind: "editable",
    label: "shared.accuracy.bonus",
    component: "number",
    defaultValue: 0,
    group: G.accuracy,
    order: 12,
    gridSize: { xs: 6, md: 6 },
    dependencies: (s) => !!s.isOffensive,
    parse: (v) => Number(v) || 0,
  },
  {
    key: "accuracy.defense",
    kind: "editable",
    label: "shared.accuracy.defense",
    component: "select",
    defaultValue: "mdef",
    group: G.accuracy,
    order: 13,
    gridSize: { xs: 6, md: 6 },
    dependencies: (s) => !!s.isOffensive,
    componentProps: {
      options: [
        { value: "def", label: "DEF" },
        { value: "mdef", label: "MDEF" },
      ],
    },
  },
  {
    key: "damage.value",
    kind: "editable",
    label: "shared.damage.value",
    component: "number",
    defaultValue: 0,
    group: G.damage,
    order: 20,
    gridSize: { xs: 6, md: 4 },
    dependencies: (s) => !!s.isOffensive,
    parse: (v) => Number(v) || 0,
  },
  {
    key: "damage.type",
    kind: "editable",
    label: "shared.damage.type",
    component: "type-select",
    defaultValue: "physical",
    group: G.damage,
    order: 21,
    gridSize: { xs: 6, md: 4 },
    dependencies: (s) => !!s.isOffensive,
    componentProps: { options: typeOptions },
  },
  {
    key: "damage.hrZero",
    kind: "editable",
    label: "shared.damage.hrZero",
    component: "checkbox",
    defaultValue: false,
    group: G.damage,
    order: 22,
    gridSize: { xs: 12, md: 4 },
    dependencies: (s) => !!s.isOffensive,
  },
  {
    key: "cost.resource",
    kind: "computed",
    label: "shared.cost.resource",
    defaultValue: "mp",
    group: G.details,
    order: 30,
  },
  {
    key: "cost.amount",
    kind: "editable",
    label: (s) =>
      s.cost?.perTarget ? "shared.cost.amountPerTarget" : "shared.cost.amount",
    component: "number",
    defaultValue: 1,
    group: G.details,
    order: 31,
    gridSize: "auto",
    parse: (v) => Number(v) || 0,
  },
  {
    key: "cost.perTarget",
    kind: "editable",
    label: "shared.cost.perTarget",
    component: "checkbox",
    defaultValue: true,
    group: G.details,
    order: 32,
    gridSize: "auto",
  },
  {
    key: "maxTargets",
    kind: "editable",
    label: prefixedLabel(NPC_SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.maxTargets),
    component: "number",
    defaultValue: 1,
    group: G.details,
    order: 33,
    gridSize: "auto",
    parse: (v) => Number(v) || 0,
    validationHints: { min: 0 },
  },
  {
    key: "duration",
    kind: "editable",
    label: prefixedLabel(NPC_SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.duration),
    component: "autocomplete",
    defaultValue: "",
    group: G.details,
    order: 34,
    gridSize: 6,
    componentProps: { options: DURATION_OPTIONS, freeSolo: true },
  },
  {
    key: "targetDescription",
    kind: "editable",
    label: prefixedLabel(NPC_SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.target),
    component: "autocomplete",
    defaultValue: "",
    group: G.details,
    order: 35,
    gridSize: 6,
    componentProps: { options: TARGET_OPTIONS, freeSolo: true },
  },
  {
    key: "effect",
    kind: "editable",
    label: prefixedLabel(NPC_SPELL_LABEL_PREFIX, SHARED_LABEL_KEYS.effect),
    component: "textarea",
    defaultValue: "",
    group: G.effect,
    order: 40,
    fullWidth: true,
  },
  ...(metaFieldConfig as unknown as ItemFieldConfig<NpcSpellFormState>),
  makePassivesTabField(
    ITEM_SCOPED_KEYS.npcSpell,
  ) as unknown as FieldConfig<NpcSpellFormState>,
  behaviorsTabField as unknown as FieldConfig<NpcSpellFormState>,
];
