const weapons = [
  {
    category: "Arcane",
    name: "Staff",
    cost: 100,
    att1: "will",
    att2: "will",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    melee: true,
  },
  {
    category: "Arcane",
    name: "Tome",
    cost: 100,
    att1: "insight",
    att2: "insight",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    melee: true,
  },
  {
    category: "Bow",
    name: "Crossbow",
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    ranged: true,
  },
  {
    category: "Bow",
    name: "Shortbow",
    cost: 200,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    ranged: true,
  },
  {
    category: "Flail",
    name: "Chain Whip",
    cost: 150,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    melee: true,
  },
  {
    category: "Firearm",
    name: "Pistol",
    cost: 250,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    ranged: true,
  },
  {
    category: "Spear",
    name: "Light Spear",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    melee: true,
  },
  {
    category: "Spear",
    name: "Heavy Spear",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 12,
    type: "physical",
    hands: 2,
    melee: true,
  },
  {
    category: "Thrown",
    name: "Shuriken",
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 4,
    type: "physical",
    hands: 1,
    ranged: true,
  },
  {
    category: "Heavy",
    name: "Iron Hammer",
    cost: 200,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
  },
  {
    category: "Heavy",
    name: "Broadaxe",
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 10,
    type: "physical",
    hands: 1,
    melee: true,
  },
  {
    category: "Heavy",
    name: "Waraxe",
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 14,
    type: "physical",
    hands: 2,
    melee: true,
  },
  {
    category: "Dagger",
    name: "Steel Dagger",
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 4,
    type: "physical",
    hands: 1,
    melee: true,
  },
  {
    category: "Brawling",
    name: "Iron Knuckle",
    cost: 150,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
  },
  {
    category: "Sword",
    name: "Katana",
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    melee: true,
  },
  {
    category: "Sword",
    name: "Bronze Sword",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
  },
  {
    category: "Sword",
    name: "Greatsword",
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    melee: true,
  },
  {
    category: "Sword",
    name: "Rapier",
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
  },
];

export default weapons;
