import { t } from "../../../translation/translate";

const weapons = [
  {
    category: t("Arcane", true),
    name: t("Staff", true),
    cost: 100,
    att1: "will",
    att2: "will",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    melee: true,
    martial: false
  },
  {
    category: t("Arcane", true),
    name: t("Tome", true),
    cost: 100,
    att1: "insight",
    att2: "insight",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 2,
    melee: true,
    martial: false
  },
  {
    category: t("Bow", true),
    name: t("Crossbow", true),
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    ranged: true,
    martial: false
  },
  {
    category: t("Bow", true),
    name: t("Shortbow", true),
    cost: 200,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    ranged: true,
    martial: false
  },
  {
    category: t("Flail", true),
    name: t("Chain Whip", true),
    cost: 150,
    att1: "dexterity",
    att2: "dexterity",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 2,
    melee: true,
    martial: false
  },
  {
    category: t("Firearm", true),
    name: t("Pistol", true),
    cost: 250,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    ranged: true,
    martial: true
  },
  {
    category: t("spear_category", true),
    name: t("Light Spear", true),
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 8,
    type: "physical",
    hands: 1,
    melee: true,
    martial: true
  },
  {
    category: t("spear_category", true),
    name: t("Heavy Spear", true),
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 12,
    type: "physical",
    hands: 2,
    melee: true,
    martial: true
  },
  {
    category: t("Thrown", true),
    name: t("Shuriken", true),
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 0,
    damage: 4,
    type: "physical",
    hands: 1,
    ranged: true,
    martial: false
  },
  {
    category: t("Heavy", true),
    name: t("Iron Hammer", true),
    cost: 200,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
    martial: false
  },
  {
    category: t("Heavy", true),
    name: t("Broadaxe", true),
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 10,
    type: "physical",
    hands: 1,
    melee: true,
    martial: true
  },
  {
    category: t("Heavy", true),
    name: t("Waraxe", true),
    cost: 250,
    att1: "might",
    att2: "might",
    prec: 0,
    damage: 14,
    type: "physical",
    hands: 2,
    melee: true,
    martial: true
  },
  {
    category: t("Dagger", true),
    name: t("Steel Dagger", true),
    cost: 150,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 4,
    type: "physical",
    hands: 1,
    melee: true,
    martial: false
  },
  {
    category: t("Brawling", true),
    name: t("Iron Knuckle", true),
    cost: 150,
    att1: "dexterity",
    att2: "might",
    prec: 0,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
    martial: false
  },
  {
    category: t("Sword", true),
    name: t("Katana", true),
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    melee: true,
    martial: true
  },
  {
    category: t("Sword", true),
    name: t("Bronze Sword", true),
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
    martial: true
  },
  {
    category: t("Sword", true),
    name: t("Greatsword", true),
    cost: 200,
    att1: "dexterity",
    att2: "might",
    prec: 1,
    damage: 10,
    type: "physical",
    hands: 2,
    melee: true,
    martial: true
  },
  {
    category: t("Sword", true),
    name: t("Rapier", true),
    cost: 200,
    att1: "dexterity",
    att2: "insight",
    prec: 1,
    damage: 6,
    type: "physical",
    hands: 1,
    melee: true,
    martial: true
  },
];

export default weapons;
